Repository kubernetes-sigs/descheduler, pull requests merged in 2018-08, with the labels that each got.

#106 Fix broken e2e tests
  hack/e2e-gce/gcloud_create_cluster.sh
Labels: cncf-cla: yes, lgtm, size/XS

#105 Low node utilization to respect priority while evicting pods
  pkg/descheduler/strategies/lownodeutilization.go
  pkg/descheduler/strategies/lownodeutilization_test.go
  test/test_utils.go
Labels: cncf-cla: yes, lgtm, size/L

#108 Fix deprecated warning in CI
  hack/e2e-gce/gcloud_create_cluster.sh
Labels: cncf-cla: yes, lgtm, size/XS

#110 Update the compatibility matrix
  README.md
Labels: cncf-cla: yes, size/XS

#111 Remove production usage warning
  README.md
Labels: cncf-cla: yes, size/XS

#113 Yaml files for kubernetes
  kubernetes/configmap.yaml
  kubernetes/job.yaml
  kubernetes/rbac.yaml
Labels: cncf-cla: yes, size/M
