Repository kubernetes-sigs/descheduler, pull requests merged in 2019-12, with the labels that each got.

#201 Fix intentation on yaml
  kubernetes/job.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#174 Documentation for compile and example yaml files for creation of kubernetes resources
  README.md
  examples/descheduler-job.yaml
  examples/descheduler.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#209 Update To Go 1.13.5
  .travis.yml
  Dockerfile
  hack/update-gofmt.sh
  hack/verify-gofmt.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
