Repository kubernetes-sigs/descheduler, pull requests merged in 2019-07, with the labels that each got.

#165 Add .gitignore to ignore output directory for binaries
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#162 Improved logic for duplicates testing
  pkg/descheduler/strategies/duplicates_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#169 Remove hardcoded node selection in E2e test
  .travis.yml
  hack/kind_config.yaml
  hack/verify-gofmt.sh
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/M
