Repository kubernetes-sigs/descheduler, pull requests merged in 2019-06, with the labels that each got.

#156 Added ownerRef.UID for evaluating duplicate Pods
  pkg/descheduler/strategies/duplicates.go
  pkg/descheduler/strategies/duplicates_test.go
  test/test_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#149 Adding golang ci lint support and Refactoring test by make it table driven
  .golangci.yml
  .travis.yml
  Makefile
  cmd/descheduler/app/version.go
  hack/verify-gofmt.sh
  pkg/descheduler/evictions/evictions_test.go
  pkg/descheduler/node/node.go
  pkg/descheduler/strategies/duplicates_test.go
  pkg/descheduler/strategies/node_affinity_test.go
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#160 Push Container Images To k8s.gcr.io
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S
