Repository kubernetes-sigs/descheduler, pull requests merged in 2020-09, with the labels that each got.

#388 Update Helm chart to v0.19.0
  charts/descheduler/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#376 Change klog to use structured logging
  pkg/descheduler/descheduler.go
  pkg/descheduler/node/node.go
  pkg/descheduler/strategies/duplicates.go
  pkg/descheduler/strategies/lownodeutilization.go
  pkg/descheduler/strategies/node_affinity.go
  pkg/descheduler/strategies/node_taint.go
  pkg/descheduler/strategies/pod_antiaffinity.go
  pkg/descheduler/strategies/pod_lifetime.go
  pkg/descheduler/strategies/toomanyrestarts.go
  pkg/utils/pod.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#392 Add Link To Helm Hub
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#395 Move IsEvictable check in PodAntiAffinity
  pkg/descheduler/strategies/pod_antiaffinity.go
  pkg/descheduler/strategies/pod_antiaffinity_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#394 Convert logs to use structured logging
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/strategies/lownodeutilization.go
  pkg/descheduler/strategies/node_affinity.go
  pkg/utils/predicates.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#393 PodLifeTime: allow custom podStatusPhases
  README.md
  examples/pod-life-time.yml
  pkg/api/types.go
  pkg/api/v1alpha1/types.go
  pkg/api/v1alpha1/zz_generated.conversion.go
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/api/zz_generated.deepcopy.go
  pkg/descheduler/strategies/pod_lifetime.go
  pkg/descheduler/strategies/pod_lifetime_test.go
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#397 Convert logs to use structured logs
  cmd/descheduler/app/server.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/node/node.go
  pkg/descheduler/policyconfig.go
  pkg/descheduler/strategies/lownodeutilization.go
  pkg/descheduler/strategies/node_affinity.go
  pkg/utils/predicates.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#384 Refactor low node utilization
  pkg/descheduler/strategies/lownodeutilization.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#401 Update e2e tests to use kind v0.9.0
  docs/contributor-guide.md
  hack/kind_config.yaml
  test/run-e2e-tests.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#402 Update e2e tests to use kind v0.9.0
  docs/contributor-guide.md
  hack/kind_config.yaml
  test/run-e2e-tests.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#403 [release-1.19] LowNodeUtilization: log when a node is unschedulable
  pkg/descheduler/strategies/lownodeutilization.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#404 [release-1.18] LowNodeUtilization: log when a node is unschedulable
  pkg/descheduler/strategies/lownodeutilization.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#406 Add Namespace filtering to RemoveDuplicates strategy
  README.md
  pkg/descheduler/strategies/duplicates.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#407 Flip Info/Infof/Error to InfoS/ErrorS
  pkg/descheduler/node/node.go
  pkg/descheduler/strategies/duplicates.go
  pkg/descheduler/strategies/lownodeutilization.go
  pkg/descheduler/strategies/node_affinity.go
  pkg/descheduler/strategies/node_taint.go
  pkg/descheduler/strategies/pod_antiaffinity.go
  pkg/descheduler/strategies/pod_lifetime.go
  pkg/descheduler/strategies/toomanyrestarts.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#411 Convert Last Log Message To Structured Logging
  pkg/descheduler/strategies/lownodeutilization.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#410 Add use case for lowNodeUtilization
  docs/user-guide.md
  examples/low-node-utilization.yml
  examples/pod-life-time.yml
Labels: approved, cncf-cla: yes, lgtm, size/M
