Repository kubernetes-sigs/descheduler, pull requests merged in 2020-06, with the labels that each got.

#315 Remove redundant tests from Travis CI
  .travis.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#312 Pass golint check for pkg/descheduler/strategies/
  pkg/descheduler/strategies/lownodeutilization.go
  pkg/descheduler/strategies/node_affinity.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/S

#310 Skip evicting when no evictable pod found on node
  pkg/descheduler/strategies/lownodeutilization.go
  pkg/descheduler/strategies/lownodeutilization_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#317 Add myself to project reviewers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#309 Make evictLocalStoragePods a property of PodEvictor
  pkg/descheduler/descheduler.go
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/evictions/evictions_test.go
  pkg/descheduler/pod/pods.go
  pkg/descheduler/pod/pods_test.go
  pkg/descheduler/strategies/duplicates.go
  pkg/descheduler/strategies/duplicates_test.go
  pkg/descheduler/strategies/lownodeutilization.go
  pkg/descheduler/strategies/lownodeutilization_test.go
  pkg/descheduler/strategies/node_affinity.go
  pkg/descheduler/strategies/node_affinity_test.go
  pkg/descheduler/strategies/node_taint.go
  pkg/descheduler/strategies/node_taint_test.go
  pkg/descheduler/strategies/pod_antiaffinity.go
  pkg/descheduler/strategies/pod_antiaffinity_test.go
  pkg/descheduler/strategies/pod_lifetime.go
  pkg/descheduler/strategies/pod_lifetime_test.go
  pkg/descheduler/strategies/toomanyrestarts.go
  pkg/descheduler/strategies/toomanyrestarts_test.go
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XL

#319 Remove redundant eviction log message and add "Reason" param to EvictPod
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/strategies/duplicates.go
  pkg/descheduler/strategies/lownodeutilization.go
  pkg/descheduler/strategies/node_affinity.go
  pkg/descheduler/strategies/node_taint.go
  pkg/descheduler/strategies/pod_antiaffinity.go
  pkg/descheduler/strategies/pod_lifetime.go
  pkg/descheduler/strategies/toomanyrestarts.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#321 Add Pod Eviction Reason To Events
  pkg/descheduler/evictions/evictions.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#325 Add initial GitHub issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/misc_request.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#322 Move sortPodsBasedOnPriority to pod util
  README.md
  pkg/descheduler/pod/pods.go
  pkg/descheduler/pod/pods_test.go
  pkg/descheduler/strategies/lownodeutilization.go
  pkg/descheduler/strategies/lownodeutilization_test.go
  pkg/descheduler/strategies/pod_antiaffinity.go
  pkg/descheduler/strategies/pod_antiaffinity_test.go
  test/test_utils.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/L

#327 Update klog to v2
  cmd/descheduler/app/server.go
  go.mod
  go.sum
  pkg/descheduler/descheduler.go
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/node/node.go
  pkg/descheduler/policyconfig.go
  pkg/descheduler/strategies/duplicates.go
  pkg/descheduler/strategies/lownodeutilization.go
  pkg/descheduler/strategies/node_affinity.go
  pkg/descheduler/strategies/node_taint.go
  pkg/descheduler/strategies/pod_antiaffinity.go
  pkg/descheduler/strategies/pod_lifetime.go
  pkg/descheduler/strategies/toomanyrestarts.go
  pkg/utils/pod.go
  pkg/utils/predicates.go
  test/e2e/e2e_test.go
  vendor/github.com/go-logr/logr/LICENSE
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/klog/v2/.gitignore
  vendor/k8s.io/klog/v2/CONTRIBUTING.md
  vendor/k8s.io/klog/v2/LICENSE
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/RELEASE.md
  vendor/k8s.io/klog/v2/SECURITY_CONTACTS
  vendor/k8s.io/klog/v2/code-of-conduct.md
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#330 examples: fix typo
  examples/policy.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
