Repository kubernetes-sigs/descheduler, pull requests merged in 2020-05, with the labels that each got.

#277 Add damemi to approvers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#276 Switch PodsHavingTooManyRestarts params to pointer
  pkg/api/types.go
  pkg/api/v1alpha1/types.go
  pkg/api/v1alpha1/zz_generated.conversion.go
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/api/zz_generated.deepcopy.go
  pkg/descheduler/strategies/toomanyrestarts.go
  pkg/descheduler/strategies/toomanyrestarts_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#278 Fix readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#274 Add New PodLifeTime Strategy
  .gitignore
  README.md
  docs/user-guide.md
  examples/pod-life-time.yml
  pkg/api/types.go
  pkg/api/v1alpha1/types.go
  pkg/api/v1alpha1/zz_generated.conversion.go
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/api/zz_generated.deepcopy.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/strategies/pod_lifetime.go
  pkg/descheduler/strategies/pod_lifetime_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#282 Update Travis CI build matrix with latest k8s point releases
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#281 Update Travis CI build matrix with latest k8s point releases
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#279 Add Additional Details To Pod Eviction Log Messages
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/evictions/evictions_test.go
  pkg/descheduler/strategies/duplicates.go
  pkg/descheduler/strategies/lownodeutilization.go
  pkg/descheduler/strategies/node_affinity.go
  pkg/descheduler/strategies/node_taint.go
  pkg/descheduler/strategies/pod_antiaffinity.go
  pkg/descheduler/strategies/pod_lifetime.go
  pkg/descheduler/strategies/toomanyrestarts.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#283 Update to k8s 1.17.5 dependencies
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/crypto/ssh/terminal/util_windows.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go
  vendor/k8s.io/client-go/discovery/discovery_client.go
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/clientcmd/api/v1/conversion.go
  vendor/k8s.io/client-go/util/connrotation/connrotation.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#275 Consider pod image in duplicates strategy
  README.md
  pkg/api/types.go
  pkg/api/v1alpha1/types.go
  pkg/api/v1alpha1/zz_generated.conversion.go
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/api/zz_generated.deepcopy.go
  pkg/descheduler/strategies/duplicates.go
  pkg/descheduler/strategies/duplicates_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#287 Mention pod eviction is in dry mode when set
  pkg/descheduler/evictions/evictions.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#289 Update Release Guide
  docs/release-guide.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#290 Update Install Manifests For Release v0.18.0
  kubernetes/cronjob.yaml
  kubernetes/job.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#291 Add URL For Viewing Staging Registry
  docs/release-guide.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#288 Update Compatibility Matrix in README
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#295 Cherry Pick: Update Compatibility Matrix in README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#297 Add verify-gofmt make target
  .travis.yml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#292 Update Install Manifests For Release v0.18.0
  kubernetes/cronjob.yaml
  kubernetes/job.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#299 Standardize node affinity strategy logs
  pkg/descheduler/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#302 Clean up code in LowNodeUtilization
  pkg/descheduler/strategies/lownodeutilization.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#285 Change break condition and thresholds validation for lowUtilization
  README.md
  pkg/descheduler/strategies/lownodeutilization.go
  pkg/descheduler/strategies/lownodeutilization_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#296 Make DeschedulerStrategy.Params a pointer
  pkg/api/types.go
  pkg/api/v1alpha1/types.go
  pkg/api/v1alpha1/zz_generated.conversion.go
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/api/zz_generated.deepcopy.go
  pkg/descheduler/strategies/duplicates.go
  pkg/descheduler/strategies/duplicates_test.go
  pkg/descheduler/strategies/lownodeutilization.go
  pkg/descheduler/strategies/lownodeutilization_test.go
  pkg/descheduler/strategies/node_affinity.go
  pkg/descheduler/strategies/node_affinity_test.go
  pkg/descheduler/strategies/pod_lifetime.go
  pkg/descheduler/strategies/pod_lifetime_test.go
  pkg/descheduler/strategies/toomanyrestarts.go
  pkg/descheduler/strategies/toomanyrestarts_test.go
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#306 Add missing address of api.StrategyParameters
  pkg/descheduler/strategies/lownodeutilization_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#307 Add parent make verify target
  .travis.yml
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#308 Download golangci-lint to _output/bin directory
  Makefile
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, priority/critical-urgent, size/XS

#300 Add more verbose logging to IsEvictable checks
  README.md
  pkg/descheduler/pod/pods.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S
