Repository kubernetes-sigs/descheduler, pull requests merged in 2020-07, with the labels that each got.

#333 Support only one sorting strategy in lowNodeUtilization
  pkg/descheduler/strategies/lownodeutilization.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/M

#332 Add maxPodsToEvictPerNode to LowNodeUtilization testcase struct
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/strategies/duplicates_test.go
  pkg/descheduler/strategies/lownodeutilization_test.go
  pkg/descheduler/strategies/node_affinity_test.go
  pkg/descheduler/strategies/node_taint_test.go
  pkg/descheduler/strategies/pod_antiaffinity_test.go
  pkg/descheduler/strategies/pod_lifetime_test.go
  pkg/descheduler/strategies/toomanyrestarts_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/L

#336 avoid appending list multiple times in RemoveDuplicates
  pkg/descheduler/strategies/duplicates.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#340 Update e2e script to use Kind setup
  test/e2e/e2e_test.go
  test/run-e2e-tests.sh
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, priority/critical-urgent, size/S

#344 e2e: have k8s version configurable when creating cluster through kind
  test/run-e2e-tests.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#345 Move kind setup to e2e script
  Makefile
  test/run-e2e-tests.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#346 Move kind setup to e2e script
  Makefile
  test/run-e2e-tests.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#342 Remove Travis CI Configuration
  .travis.yml
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#298 Add Helm chart
  .github/workflows/release.yaml
  Makefile
  charts/descheduler/.helmignore
  charts/descheduler/Chart.yaml
  charts/descheduler/README.md
  charts/descheduler/templates/NOTES.txt
  charts/descheduler/templates/_helpers.tpl
  charts/descheduler/templates/clusterrole.yaml
  charts/descheduler/templates/clusterrolebinding.yaml
  charts/descheduler/templates/configmap.yaml
  charts/descheduler/templates/cronjob.yaml
  charts/descheduler/templates/serviceaccount.yaml
  charts/descheduler/values.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/L

#349 Cherry Pick: Remove Travis CI Configuration release-1.18 Branch
  .travis.yml
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#350 Cherry Pick: Remove Travis CI Configuration release-1.17 Branch
  .travis.yml
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#351 Update Release Documentation For Helm Charts
  charts/descheduler/Chart.yaml
  docs/release-guide.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#352 Cherry Pick: Add helm chart release-1.18
  .github/workflows/release.yaml
  Makefile
  charts/descheduler/.helmignore
  charts/descheduler/Chart.yaml
  charts/descheduler/README.md
  charts/descheduler/templates/NOTES.txt
  charts/descheduler/templates/_helpers.tpl
  charts/descheduler/templates/clusterrole.yaml
  charts/descheduler/templates/clusterrolebinding.yaml
  charts/descheduler/templates/configmap.yaml
  charts/descheduler/templates/cronjob.yaml
  charts/descheduler/templates/serviceaccount.yaml
  charts/descheduler/values.yaml
  docs/release-guide.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#343 Clean e2e test so it's easier to extend it
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#354 Bump Helm chart to version 0.18.1
  charts/descheduler/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#356 Update Helm release action to work on release branches
  .github/workflows/release.yaml
  charts/descheduler/Chart.yaml
  docs/release-guide.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#357 [release-1.18] Update Helm release action to work on release branches
  .github/workflows/release.yaml
  charts/descheduler/Chart.yaml
  docs/release-guide.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#358 Update helm chart name in docs
  charts/descheduler/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#360 Add NPD+CA autohealing use case to user guide
  docs/user-guide.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#359 More Helm Documentation
  README.md
  charts/descheduler/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#338 Filter pods by namespaces
  README.md
  pkg/api/types.go
  pkg/api/v1alpha1/types.go
  pkg/api/v1alpha1/zz_generated.conversion.go
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/api/zz_generated.deepcopy.go
  pkg/descheduler/pod/pods.go
  pkg/descheduler/pod/pods_test.go
  pkg/descheduler/strategies/duplicates.go
  pkg/descheduler/strategies/lownodeutilization.go
  pkg/descheduler/strategies/node_affinity.go
  pkg/descheduler/strategies/node_taint.go
  pkg/descheduler/strategies/pod_antiaffinity.go
  pkg/descheduler/strategies/pod_lifetime.go
  pkg/descheduler/strategies/toomanyrestarts.go
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XL

#361 remove unnecessary line feed in log messages
  pkg/descheduler/strategies/lownodeutilization_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#362 Update version parsing to exclude helm-chart tags
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#363 Update Container Registry to k8s.gcr.io
  charts/descheduler/README.md
  charts/descheduler/values.yaml
  docs/user-guide.md
  kubernetes/cronjob.yaml
  kubernetes/job.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#366 Add missing validation in PodAntiAffinity
  pkg/descheduler/strategies/pod_antiaffinity.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS
