Repository kubernetes-sigs/descheduler, pull requests merged in 2020-02, with the labels that each got.

#221 Wire --descheduling-interval to run descheduler on a loop
  cmd/descheduler/app/options/options.go
  pkg/descheduler/descheduler.go
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#217 Automate Container Image Builds Using GCB
  cloudbuild.yaml
  docs/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#223 Update to Go 1.13.6
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#227 Remove reference to critical-pod annotation from documentation
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#234 Critical pod annotation scheduler.alpha.kubernetes.io/critical-pod has been drop, no need to set it anymore in the tests
  pkg/descheduler/pod/pods_test.go
  pkg/descheduler/strategies/duplicates_test.go
  pkg/descheduler/strategies/lownodeutilization_test.go
  pkg/descheduler/strategies/node_taint_test.go
  test/test_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#226 Fix typo in function name
  pkg/descheduler/node/node.go
  pkg/descheduler/node/node_test.go
  pkg/descheduler/strategies/lownodeutilization.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#215 fix Build and Run GOPATH dir
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#208 Streamline Deployment Docs For End Users
  README.md
  examples/descheduler-job.yaml
  examples/descheduler.yaml
  kubernetes/configmap.yaml
  kubernetes/cronjob.yaml
  kubernetes/job.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#236 Fix makefile for make gen, and update hack files and auto-generated files.
  Makefile
  hack/update-generated-conversions.sh
  hack/update-generated-deep-copies.sh
  hack/update-generated-defaulters.sh
  pkg/api/v1alpha1/zz_generated.conversion.go
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/api/v1alpha1/zz_generated.defaults.go
  pkg/api/zz_generated.deepcopy.go
  pkg/apis/componentconfig/v1alpha1/zz_generated.conversion.go
  pkg/apis/componentconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/componentconfig/v1alpha1/zz_generated.defaults.go
  pkg/apis/componentconfig/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#237 Update ClusterRole To Allow Creating Events
  kubernetes/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#222 Run e2e Tests Against Multiple k8s Versions
  .travis.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#239 Fix email address in docker files.
  Dockerfile
  Dockerfile.dev
Labels: approved, cncf-cla: yes, lgtm, size/XS

#242 Fix GCR Image Location In Job and CronJob YAML
  kubernetes/cronjob.yaml
  kubernetes/job.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#233 Add notes section to release documentation
  docs/releasing.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S
