Repository kubernetes-sigs/descheduler, pull requests merged in 2020-12, with the labels that each got.

#448 Add more topology spread logs
  pkg/descheduler/strategies/topologyspreadconstraint.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#452 Bump To Go 1.15.5
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#449 Enable Multi-Arch Container Image Builds
  Dockerfile
  Makefile
  cloudbuild.yaml
  docs/release-guide.md
  docs/user-guide.md
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#454 Fix broken namespace logic in TopologySpreadConstraint
  pkg/descheduler/strategies/topologyspreadconstraint.go
  pkg/descheduler/strategies/topologyspreadconstraint_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, size/M

#455 Helm: allow the topologySpreadConstraint strategy to list namespaces
  charts/descheduler/templates/clusterrole.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#458 Helm chart rename - Step #1
  .github/workflows/release.yaml
  charts/descheduler/Chart.yaml
  charts/descheduler/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#457 Helm chart rename - Step #2
  .github/workflows/release.yaml
  charts/descheduler/Chart.yaml
  charts/descheduler/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#453 Allow setting options successfulJobsHistoryLimit and failedJobsHistoryLimit for cronjob
  charts/descheduler/Chart.yaml
  charts/descheduler/README.md
  charts/descheduler/templates/cronjob.yaml
  charts/descheduler/values.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#462 Update Docs and Manifests for v0.20.0
  README.md
  kubernetes/cronjob/cronjob.yaml
  kubernetes/job/job.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#464 Bump to v0.20.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/M

#465 Skip topology calculations if domains are already balanced
  pkg/descheduler/strategies/topologyspreadconstraint.go
  pkg/descheduler/strategies/topologyspreadconstraint_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#463 RemoveDuplicatePods: evict uniformly
  pkg/descheduler/strategies/duplicates.go
  pkg/descheduler/strategies/duplicates_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/L

#468 Run as user 1000 so pod can be runAsNonRoot for security purposes
  Dockerfile
  Dockerfile.dev
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#471 refactor: remove unused code
  pkg/descheduler/descheduler.go
  pkg/descheduler/node/node.go
  pkg/descheduler/node/node_test.go
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
