Repository kubernetes-sigs/descheduler, pull requests merged in 2020-10, with the labels that each got.

#414 Update Event Logging to Use Structured Logging
  pkg/descheduler/evictions/evictions.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#416 Bump To Go 1.15.2
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#417 Helm chart README fix
  charts/descheduler/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#421 Support for remote resources in kustomize
  README.md
  kubernetes/base/configmap.yaml
  kubernetes/base/kustomization.yaml
  kubernetes/base/rbac.yaml
  kubernetes/cronjob/cronjob.yaml
  kubernetes/cronjob/kustomization.yaml
  kubernetes/job/job.yaml
  kubernetes/job/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#418 charts/descheduler: add PodSecurityPolicy support
  charts/descheduler/README.md
  charts/descheduler/templates/clusterrole.yaml
  charts/descheduler/templates/podsecuritypolicy.yaml
  charts/descheduler/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#429 pkg/descheduler/strategies: fix typo
  pkg/descheduler/pod/pods.go
  pkg/descheduler/strategies/lownodeutilization.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#430 Add hack/verify-spelling.sh script and Makefile target
  Makefile
  go.mod
  go.sum
  hack/.spelling_failures
  hack/tools.go
  hack/verify-spelling.sh
  vendor/github.com/client9/misspell/.gitignore
  vendor/github.com/client9/misspell/.travis.yml
  vendor/github.com/client9/misspell/Dockerfile
  vendor/github.com/client9/misspell/Gopkg.lock
  vendor/github.com/client9/misspell/Gopkg.toml
  vendor/github.com/client9/misspell/LICENSE
  vendor/github.com/client9/misspell/Makefile
  vendor/github.com/client9/misspell/README.md
  vendor/github.com/client9/misspell/RELEASE-HOWTO.md
  vendor/github.com/client9/misspell/ascii.go
  vendor/github.com/client9/misspell/case.go
  vendor/github.com/client9/misspell/cmd/misspell/main.go
  vendor/github.com/client9/misspell/goreleaser.yml
  vendor/github.com/client9/misspell/install-misspell.sh
  vendor/github.com/client9/misspell/legal.go
  vendor/github.com/client9/misspell/mime.go
  vendor/github.com/client9/misspell/notwords.go
  vendor/github.com/client9/misspell/replace.go
  vendor/github.com/client9/misspell/stringreplacer.go
  vendor/github.com/client9/misspell/stringreplacer_test.gox
  vendor/github.com/client9/misspell/url.go
  vendor/github.com/client9/misspell/words.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL
