Repository kubernetes-sigs/descheduler, pull requests merged in 2020-08, with the labels that each got.

#369 Add check for ownerref length in DuplicatePods strategy
  pkg/descheduler/strategies/duplicates.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, size/XS

#364 Allow custom priority threshold
  README.md
  charts/descheduler/templates/clusterrole.yaml
  kubernetes/rbac.yaml
  pkg/api/types.go
  pkg/api/v1alpha1/types.go
  pkg/api/v1alpha1/zz_generated.conversion.go
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/api/zz_generated.deepcopy.go
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/evictions/evictions_test.go
  pkg/descheduler/strategies/duplicates.go
  pkg/descheduler/strategies/lownodeutilization.go
  pkg/descheduler/strategies/node_affinity.go
  pkg/descheduler/strategies/node_taint.go
  pkg/descheduler/strategies/pod_antiaffinity.go
  pkg/descheduler/strategies/pod_lifetime.go
  pkg/descheduler/strategies/toomanyrestarts.go
  pkg/utils/pod.go
  pkg/utils/priority.go
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#374 Promote Namespaces field to a pointer
  pkg/api/types.go
  pkg/api/v1alpha1/types.go
  pkg/api/v1alpha1/zz_generated.conversion.go
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/api/zz_generated.deepcopy.go
  pkg/descheduler/strategies/node_affinity.go
  pkg/descheduler/strategies/node_taint.go
  pkg/descheduler/strategies/pod_antiaffinity.go
  pkg/descheduler/strategies/pod_lifetime.go
  pkg/descheduler/strategies/toomanyrestarts.go
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#375 Update Maintainer Details In Helm Chart
  charts/descheduler/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#372 Redefine IsEvictable to be customizable for a particular strategy
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/evictions/evictions_test.go
  pkg/descheduler/pod/pods.go
  pkg/descheduler/strategies/duplicates.go
  pkg/descheduler/strategies/lownodeutilization.go
  pkg/descheduler/strategies/node_affinity.go
  pkg/descheduler/strategies/node_taint.go
  pkg/descheduler/strategies/pod_antiaffinity.go
  pkg/descheduler/strategies/pod_lifetime.go
  pkg/descheduler/strategies/toomanyrestarts.go
  pkg/utils/pod.go
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#382 Add table of contents to README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#386 Bump k8s Modules For k8s 1.19
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/go.mod
  vendor/github.com/evanphx/json-patch/go.sum
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/k8s.io/apimachinery/pkg/runtime/converter.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/util/net/util.go
  vendor/k8s.io/code-generator/go.mod
  vendor/k8s.io/code-generator/go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/structured-merge-diff/v4/LICENSE
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/allocator.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/doc.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/fields.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/jsontagutil.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/list.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/listreflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/listunstructured.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/map.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/mapreflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/mapunstructured.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/reflectcache.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/scalar.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/structreflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/value.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/valuereflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/valueunstructured.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#387 Add KUBECONFIG Export To Contributing Docs
  docs/contributor-guide.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#385 LowNodeUtilization: use clientset in testing, drop all custom reactors
  pkg/descheduler/pod/pods.go
  pkg/descheduler/strategies/lownodeutilization_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#371 Update To Go 1.15.0
  Dockerfile
  Makefile
  docs/contributor-guide.md
  go.mod
  hack/update-gofmt.sh
  hack/verify-gofmt.sh
  pkg/descheduler/node/node_test.go
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#389 Update Docs and Manifests for v0.19.0
  README.md
  kubernetes/cronjob.yaml
  kubernetes/job.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
