Repository kubernetes-sigs/descheduler, pull requests merged in 2020-04, with the labels that each got.

#255 Update to Go 1.13.9
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#256 Fix early return from PodFitsAnyNode check
  pkg/descheduler/node/node.go
  pkg/descheduler/node/node_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, size/M

#260 fix broken link :
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#264 readme: RemovePodsViolatingNodeAffinity: reword description of the strategy
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#262 Order pods by priority only over over utilized nodes
  pkg/descheduler/descheduler_test.go
  pkg/descheduler/evictions/evictions_test.go
  pkg/descheduler/node/node_test.go
  pkg/descheduler/pod/pods_test.go
  pkg/descheduler/strategies/duplicates_test.go
  pkg/descheduler/strategies/lownodeutilization.go
  pkg/descheduler/strategies/lownodeutilization_test.go
  pkg/descheduler/strategies/node_affinity_test.go
  pkg/descheduler/strategies/node_taint_test.go
  pkg/descheduler/strategies/pod_antiaffinity_test.go
  test/test_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#265 Tolerations taints code cleanup
  pkg/descheduler/strategies/node_taint.go
  pkg/descheduler/strategies/node_taint_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#266 Move maximum-pods-per-nodes-evicted logic under a single invocation
  pkg/descheduler/descheduler.go
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/strategies/duplicates.go
  pkg/descheduler/strategies/duplicates_test.go
  pkg/descheduler/strategies/lownodeutilization.go
  pkg/descheduler/strategies/lownodeutilization_test.go
  pkg/descheduler/strategies/node_affinity.go
  pkg/descheduler/strategies/node_affinity_test.go
  pkg/descheduler/strategies/node_taint.go
  pkg/descheduler/strategies/node_taint_test.go
  pkg/descheduler/strategies/pod_antiaffinity.go
  pkg/descheduler/strategies/pod_antiaffinity_test.go
  pkg/utils/utils.go
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#254 Add RemoveTooManyRestarts policy
  .gitignore
  README.md
  examples/policy.yaml
  go.mod
  go.sum
  pkg/api/types.go
  pkg/api/v1alpha1/types.go
  pkg/api/v1alpha1/zz_generated.conversion.go
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/api/zz_generated.deepcopy.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/strategies/toomanyrestarts.go
  pkg/descheduler/strategies/toomanyrestarts_test.go
  vendor/github.com/gogo/protobuf/proto/encode.go
  vendor/github.com/gogo/protobuf/proto/lib.go
  vendor/github.com/gogo/protobuf/proto/properties.go
  vendor/github.com/gogo/protobuf/proto/table_marshal.go
  vendor/github.com/gogo/protobuf/proto/table_merge.go
  vendor/github.com/gogo/protobuf/proto/table_unmarshal.go
  vendor/github.com/gogo/protobuf/proto/text.go
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
  vendor/modules.txt
  vendor/sigs.k8s.io/yaml/.travis.yml
  vendor/sigs.k8s.io/yaml/OWNERS
  vendor/sigs.k8s.io/yaml/README.md
  vendor/sigs.k8s.io/yaml/go.mod
  vendor/sigs.k8s.io/yaml/go.sum
  vendor/sigs.k8s.io/yaml/yaml.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XL

#240 Turn StrategyParameters.NodeResourceUtilizationThresholds field into a pointer
  pkg/api/types.go
  pkg/api/v1alpha1/types.go
  pkg/api/v1alpha1/zz_generated.conversion.go
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/api/zz_generated.deepcopy.go
  pkg/descheduler/strategies/lownodeutilization.go
  pkg/descheduler/strategies/lownodeutilization_test.go
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#267 Drop descheduler server from strategies
  pkg/descheduler/descheduler.go
  pkg/descheduler/strategies/duplicates.go
  pkg/descheduler/strategies/duplicates_test.go
  pkg/descheduler/strategies/lownodeutilization.go
  pkg/descheduler/strategies/lownodeutilization_test.go
  pkg/descheduler/strategies/node_affinity.go
  pkg/descheduler/strategies/node_affinity_test.go
  pkg/descheduler/strategies/node_taint.go
  pkg/descheduler/strategies/node_taint_test.go
  pkg/descheduler/strategies/pod_antiaffinity.go
  pkg/descheduler/strategies/pod_antiaffinity_test.go
  pkg/descheduler/strategies/toomanyrestarts.go
  pkg/descheduler/strategies/toomanyrestarts_test.go
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
