Repository kubernetes-sigs/descheduler, pull requests merged in 2020-03, with the labels that each got.

#244 Documentation Refresh
  README.md
  docs/README.md
  docs/contributor-guide.md
  docs/release-guide.md
  docs/user-guide.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#249 List nodes through informer in every iteration
  pkg/descheduler/descheduler.go
  pkg/descheduler/descheduler_test.go
  pkg/descheduler/node/node.go
  pkg/descheduler/node/node_test.go
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#181 Respect Node taints with tolerations (if exist)
  pkg/descheduler/strategies/lownodeutilization.go
  pkg/descheduler/strategies/lownodeutilization_test.go
  pkg/utils/pod.go
  pkg/utils/predicates.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/L

#246 Update to Go 1.13.8
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS
