Repository kubernetes-sigs/descheduler, pull requests merged in 2021-08, with the labels that each got.

#611 Update README to remove redundant list of strategies
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#599 Update GCE images to Ubuntu 18.04 LTS
  hack/e2e-gce/gcloud_create_cluster.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#602 TopologySpreadConstraint: advance above avg index when at ideal average
  pkg/descheduler/strategies/topologyspreadconstraint.go
  pkg/descheduler/strategies/topologyspreadconstraint_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#582 Update helm chart for running as deployment
  charts/descheduler/README.md
  charts/descheduler/templates/_helpers.tpl
  charts/descheduler/templates/cronjob.yaml
  charts/descheduler/templates/deployment.yaml
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#592 docs: adding clarification to HighNodeUtilization's purpose
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#614 Bump To Go 1.16.7
  Dockerfile
Labels: cncf-cla: yes, size/XS, lgtm, kind/cleanup, approved

#613 nodeutilization strategy: "numberOfNodes" should work as documented
  pkg/descheduler/strategies/nodeutilization/highnodeutilization.go
  pkg/descheduler/strategies/nodeutilization/lownodeutilization.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#610 Introduce RemoveFailedPods strategy
  README.md
  examples/failed-pods.yaml
  pkg/api/types.go
  pkg/api/v1alpha1/types.go
  pkg/api/v1alpha1/zz_generated.conversion.go
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/api/zz_generated.deepcopy.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/pod/pods.go
  pkg/descheduler/strategies/failedpods.go
  pkg/descheduler/strategies/failedpods_test.go
  pkg/descheduler/strategies/topologyspreadconstraint.go
  pkg/descheduler/strategies/validation/strategyparams.go
  pkg/descheduler/strategies/validation/strategyparams_test.go
Labels: cncf-cla: yes, size/XL, lgtm, approved, ok-to-test

#597 Add e2e tests for TopologySpreadConstraint
  hack/e2e-gce/gcloud_create_cluster.sh
  hack/kind_config.yaml
  test/e2e/e2e_test.go
  test/e2e/e2e_topologyspreadconstraint_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#617 Update Docs and Manifests for v0.22.0
  README.md
  docs/user-guide.md
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/documentation
