Repository kubernetes-sigs/descheduler, pull requests merged in 2021-01, with the labels that each got.

#478 Update README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#482 Add Logging field to v1alpha1 componentconfig
  pkg/api/v1alpha1/zz_generated.conversion.go
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/api/v1alpha1/zz_generated.defaults.go
  pkg/api/zz_generated.deepcopy.go
  pkg/apis/componentconfig/v1alpha1/types.go
  pkg/apis/componentconfig/v1alpha1/zz_generated.conversion.go
  pkg/apis/componentconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/componentconfig/v1alpha1/zz_generated.defaults.go
  pkg/apis/componentconfig/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/important-soon, size/S

#484 Fix TopologySpread bug that evicts non-evictable pods
  pkg/descheduler/strategies/topologyspreadconstraint.go
  pkg/descheduler/strategies/topologyspreadconstraint_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, size/M

#474 Add a parameter to include soft topology spread constraints
  README.md
  pkg/api/types.go
  pkg/api/v1alpha1/types.go
  pkg/api/v1alpha1/zz_generated.conversion.go
  pkg/descheduler/strategies/topologyspreadconstraint.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#481 Add option to ignore pods with PVCs from eviction
  README.md
  pkg/api/types.go
  pkg/api/v1alpha1/types.go
  pkg/api/v1alpha1/zz_generated.conversion.go
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/api/zz_generated.deepcopy.go
  pkg/apis/componentconfig/types.go
  pkg/apis/componentconfig/v1alpha1/types.go
  pkg/apis/componentconfig/v1alpha1/zz_generated.conversion.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/strategies/duplicates_test.go
  pkg/descheduler/strategies/lownodeutilization_test.go
  pkg/descheduler/strategies/node_affinity_test.go
  pkg/descheduler/strategies/node_taint_test.go
  pkg/descheduler/strategies/pod_antiaffinity_test.go
  pkg/descheduler/strategies/pod_lifetime_test.go
  pkg/descheduler/strategies/toomanyrestarts_test.go
  pkg/descheduler/strategies/topologyspreadconstraint_test.go
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L
