Repository kubernetes-sigs/descheduler, pull requests merged in 2021-12, with the labels that each got.

#658 Add maxNoOfPodsToEvictPerNamespace policy
  pkg/api/types.go
  pkg/api/v1alpha1/types.go
  pkg/api/v1alpha1/zz_generated.conversion.go
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/api/zz_generated.deepcopy.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/strategies/duplicates_test.go
  pkg/descheduler/strategies/failedpods_test.go
  pkg/descheduler/strategies/node_affinity_test.go
  pkg/descheduler/strategies/node_taint_test.go
  pkg/descheduler/strategies/nodeutilization/highnodeutilization_test.go
  pkg/descheduler/strategies/nodeutilization/lownodeutilization_test.go
  pkg/descheduler/strategies/pod_antiaffinity_test.go
  pkg/descheduler/strategies/pod_lifetime_test.go
  pkg/descheduler/strategies/toomanyrestarts_test.go
  pkg/descheduler/strategies/topologyspreadconstraint_test.go
  test/e2e/e2e_duplicatepods_test.go
  test/e2e/e2e_test.go
  test/e2e/e2e_toomanyrestarts_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#673 list pods assigned to a node by pod informer cache
  pkg/descheduler/descheduler.go
  pkg/descheduler/descheduler_test.go
  pkg/descheduler/pod/pods.go
  pkg/descheduler/pod/pods_test.go
  pkg/descheduler/strategies/duplicates.go
  pkg/descheduler/strategies/duplicates_test.go
  pkg/descheduler/strategies/failedpods.go
  pkg/descheduler/strategies/failedpods_test.go
  pkg/descheduler/strategies/node_affinity.go
  pkg/descheduler/strategies/node_affinity_test.go
  pkg/descheduler/strategies/node_taint.go
  pkg/descheduler/strategies/node_taint_test.go
  pkg/descheduler/strategies/nodeutilization/highnodeutilization.go
  pkg/descheduler/strategies/nodeutilization/highnodeutilization_test.go
  pkg/descheduler/strategies/nodeutilization/lownodeutilization.go
  pkg/descheduler/strategies/nodeutilization/lownodeutilization_test.go
  pkg/descheduler/strategies/nodeutilization/nodeutilization.go
  pkg/descheduler/strategies/pod_antiaffinity.go
  pkg/descheduler/strategies/pod_antiaffinity_test.go
  pkg/descheduler/strategies/pod_lifetime.go
  pkg/descheduler/strategies/pod_lifetime_test.go
  pkg/descheduler/strategies/toomanyrestarts.go
  pkg/descheduler/strategies/toomanyrestarts_test.go
  pkg/descheduler/strategies/topologyspreadconstraint.go
  pkg/descheduler/strategies/topologyspreadconstraint_test.go
  test/e2e/e2e_duplicatepods_test.go
  test/e2e/e2e_failedpods_test.go
  test/e2e/e2e_test.go
  test/e2e/e2e_toomanyrestarts_test.go
  test/e2e/e2e_topologyspreadconstraint_test.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved, ok-to-test

#678 fix: install golangci using from the golangci repo
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#670 Add node name label to the counter metric for evicted pods
  metrics/metrics.go
  pkg/descheduler/evictions/evictions.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#680 Set the klog output to stdout by default
  cmd/descheduler/descheduler.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#661 Add pod.Status.Reason to the list of reasons
  pkg/descheduler/strategies/failedpods.go
  pkg/descheduler/strategies/failedpods_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#682 commonLabels value for chart
  charts/descheduler/README.md
  charts/descheduler/templates/_helpers.tpl
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test
