Repository kubernetes-sigs/descheduler, pull requests merged in 2021-04, with the labels that each got.

#541 Update Generated Code
  pkg/api/v1alpha1/zz_generated.conversion.go
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/api/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#543 e2e_test: fix goroutine leak
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#434 Support extended resources in LowNodeUtilization
  README.md
  pkg/descheduler/strategies/lownodeutilization.go
  pkg/descheduler/strategies/lownodeutilization_test.go
  test/test_utils.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/L

#544 LNU: improve nodeUsage logging
  README.md
  pkg/descheduler/strategies/lownodeutilization.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#507 Add verify scripts for make gen to run during PR
  Makefile
  hack/verify-conversions.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/M

#546 Add diagram of strategies
  README.md
  strategies_diagram.png
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#548 Updating policy api version used in pod evictor
  pkg/descheduler/strategies/duplicates_test.go
  pkg/descheduler/strategies/lownodeutilization_test.go
  pkg/descheduler/strategies/node_affinity_test.go
  pkg/descheduler/strategies/node_taint_test.go
  pkg/descheduler/strategies/pod_antiaffinity_test.go
  pkg/descheduler/strategies/pod_lifetime_test.go
  pkg/descheduler/strategies/toomanyrestarts_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/S

#537 Update Docs and Manifests for v0.21.0
  README.md
  docs/user-guide.md
  kubernetes/cronjob/cronjob.yaml
  kubernetes/job/job.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#554 code cleanup: remove check on length
  pkg/utils/predicates.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#556 Invert main strategy loop for performance and customizability
  pkg/descheduler/descheduler.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#558 Use Structured Logging For Unknown Strategy Log Message
  pkg/descheduler/descheduler.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS
