Repository kubernetes-sigs/descheduler, pull requests merged in 2021-11, with the labels that each got.

#639 Ignore Pods With Deletion Timestamp
  README.md
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/strategies/failedpods_test.go
  pkg/descheduler/strategies/node_affinity_test.go
  pkg/descheduler/strategies/pod_antiaffinity_test.go
  pkg/descheduler/strategies/pod_lifetime_test.go
  pkg/descheduler/strategies/topologyspreadconstraint.go
  pkg/utils/pod.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#662 Drop deprecated flags
  cmd/descheduler/app/options/options.go
  pkg/api/types.go
  pkg/api/v1alpha1/zz_generated.conversion.go
  pkg/api/zz_generated.deepcopy.go
  pkg/apis/componentconfig/v1alpha1/types.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/strategies/duplicates_test.go
  pkg/descheduler/strategies/failedpods_test.go
  pkg/descheduler/strategies/node_affinity_test.go
  pkg/descheduler/strategies/node_taint_test.go
  pkg/descheduler/strategies/nodeutilization/highnodeutilization_test.go
  pkg/descheduler/strategies/nodeutilization/lownodeutilization_test.go
  pkg/descheduler/strategies/pod_antiaffinity_test.go
  pkg/descheduler/strategies/pod_lifetime_test.go
  pkg/descheduler/strategies/toomanyrestarts_test.go
  pkg/descheduler/strategies/topologyspreadconstraint_test.go
  test/e2e/e2e_duplicatepods_test.go
  test/e2e/e2e_failedpods_test.go
  test/e2e/e2e_test.go
  test/e2e/e2e_toomanyrestarts_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#664 fix typo minPodLifeTimeSeconds
  README.md
  examples/failed-pods.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#665 images: use k8s-staging-test-infra/gcb-docker-gcloud
  cloudbuild.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved
