Repository kubernetes-sigs/descheduler, pull requests merged in 2021-03, with the labels that each got.

#509 Add lixiang233 As A Reviewer
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#512 Bump github.com/gogo/protobuf to v1.3.2
  go.mod
  go.sum
  vendor/github.com/gogo/protobuf/proto/text_parser.go
  vendor/golang.org/x/tools/go/ast/astutil/util.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/event/core/event.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/gocommand/version.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/golang.org/x/tools/internal/imports/sortimports.go
  vendor/golang.org/x/tools/internal/imports/zstdlib.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XL

#490 Add default logging-format value
  cmd/descheduler/app/options/options.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#510 Filter pods by labelSelector
  README.md
  pkg/api/types.go
  pkg/api/v1alpha1/types.go
  pkg/api/v1alpha1/zz_generated.conversion.go
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/api/zz_generated.deepcopy.go
  pkg/descheduler/pod/pods.go
  pkg/descheduler/pod/pods_test.go
  pkg/descheduler/strategies/node_affinity.go
  pkg/descheduler/strategies/node_taint.go
  pkg/descheduler/strategies/pod_antiaffinity.go
  pkg/descheduler/strategies/pod_lifetime.go
  pkg/descheduler/strategies/pod_lifetime_test.go
  pkg/descheduler/strategies/toomanyrestarts.go
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#515 Clarify resource percentage calculation in README
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#517 Correct log in topology spread strategy
  pkg/descheduler/strategies/topologyspreadconstraint.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#521 Enable ARM32v7 Container Image Builds
  Makefile
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#508 Move Inactive Maintainers to Emeritus Status
  Dockerfile
  Dockerfile.dev
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/S

#525 (TopologySpread) Evict pods with selectors that match multiple nodes
  pkg/descheduler/strategies/topologyspreadconstraint.go
  pkg/descheduler/strategies/topologyspreadconstraint_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#526 Correct Helm Chart Docs For Container Requests and Limits
  charts/descheduler/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#520 Document That Descheduler Considers StatefulSets For Eviction
  README.md
  pkg/descheduler/evictions/evictions_test.go
  test/test_utils.go
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#533 Bump go to 1.16
  Dockerfile
  docs/contributor-guide.md
  go.mod
  go.sum
  hack/update-gofmt.sh
  hack/verify-gofmt.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#534 Use Tags In Kustomize Documentation
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#523 Added EvictSystemCriticalPods flag to descheduler
  .gitignore
  README.md
  pkg/api/types.go
  pkg/api/v1alpha1/types.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/evictions/evictions_test.go
  pkg/descheduler/strategies/duplicates_test.go
  pkg/descheduler/strategies/lownodeutilization_test.go
  pkg/descheduler/strategies/node_affinity_test.go
  pkg/descheduler/strategies/node_taint_test.go
  pkg/descheduler/strategies/pod_antiaffinity_test.go
  pkg/descheduler/strategies/pod_lifetime_test.go
  pkg/descheduler/strategies/toomanyrestarts_test.go
  pkg/descheduler/strategies/topologyspreadconstraint_test.go
  pkg/utils/pod.go
  test/e2e/e2e_test.go
  test/run-e2e-tests.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL
