Repository kubernetes-sigs/descheduler, pull requests merged in 2021-07, with the labels that each got.

#594 Rename master to main
  docs/release-guide.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#600 Add example for RemovePodsViolatingTopologySpreadConstraint
  examples/high-node-utilization.yml
  examples/low-node-utilization.yml
  examples/pod-life-time.yml
  examples/policy.yaml
  examples/topology-spread-constraint.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#562 Add tolerations to cronjob in helm chart
  charts/descheduler/README.md
  charts/descheduler/templates/cronjob.yaml
  charts/descheduler/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#598 Clean up extra spaces
  hack/e2e-gce/gcloud_create_cluster.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
