Repository kubernetes-sigs/descheduler, pull requests merged in 2021-02, with the labels that each got.

#493 Modify resourceUsage.Value() to resourceUsage.MilliValue()
  pkg/descheduler/strategies/lownodeutilization.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#480 Add nodeSelector to cronJob helm chart
  charts/descheduler/README.md
  charts/descheduler/templates/cronjob.yaml
  charts/descheduler/values.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#495 Update Job and CronJob YAML to run as non-root
  kubernetes/cronjob/cronjob.yaml
  kubernetes/job/job.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#497 LowNodeUtilization: unit test resourceUsagePercentages to validate percentages are computed correctly
  pkg/descheduler/strategies/lownodeutilization_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#496 Update Helm Chart to run as non-root
  charts/descheduler/templates/cronjob.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#498 Fix indentation in values.yaml
  charts/descheduler/values.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#499 Bump To Go 1.15.8
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#502 Move 'total pods evicted' log message to main loop
  pkg/descheduler/descheduler.go
  pkg/descheduler/strategies/lownodeutilization.go
  pkg/descheduler/strategies/node_affinity.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#504 Log and README optimization for LowNodeUtilization
  README.md
  pkg/descheduler/strategies/lownodeutilization.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#506 Update e2e tests to use kind v0.10.0
  docs/contributor-guide.md
  test/run-e2e-tests.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
