Repository kubernetes-sigs/descheduler, pull requests merged in 2022-01, with the labels that each got.

#689 run ./hack/update-* scripts
  pkg/api/v1alpha1/zz_generated.conversion.go
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/api/v1alpha1/zz_generated.defaults.go
  pkg/api/zz_generated.deepcopy.go
  pkg/apis/componentconfig/v1alpha1/zz_generated.conversion.go
  pkg/apis/componentconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/componentconfig/v1alpha1/zz_generated.defaults.go
  pkg/apis/componentconfig/zz_generated.deepcopy.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#687 Comment update for metrics
  metrics/metrics.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#691 Eliminated race condition in E2E tests
  test/e2e/e2e_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#693 Update NOTES.txt
  charts/descheduler/templates/NOTES.txt
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#692 NonSlidingUntil for deployment
  pkg/descheduler/descheduler.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#695 make livenessprobe consistent across manifests
  charts/descheduler/templates/cronjob.yaml
  charts/descheduler/templates/deployment.yaml
  charts/descheduler/values.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#677 Use a fake client when evicting pods by individual strategies to accumulate the evictions
  pkg/descheduler/descheduler.go
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/evictions/evictions_test.go
  pkg/descheduler/strategies/duplicates_test.go
  pkg/descheduler/strategies/failedpods_test.go
  pkg/descheduler/strategies/node_affinity_test.go
  pkg/descheduler/strategies/node_taint_test.go
  pkg/descheduler/strategies/nodeutilization/highnodeutilization_test.go
  pkg/descheduler/strategies/nodeutilization/lownodeutilization_test.go
  pkg/descheduler/strategies/pod_antiaffinity_test.go
  pkg/descheduler/strategies/pod_lifetime_test.go
  pkg/descheduler/strategies/toomanyrestarts_test.go
  pkg/descheduler/strategies/topologyspreadconstraint_test.go
  test/e2e/e2e_duplicatepods_test.go
  test/e2e/e2e_test.go
  test/e2e/e2e_toomanyrestarts_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#699 Evictor: report successful eviction independently of the dry-mode
  pkg/descheduler/evictions/evictions.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#700 Use the root context cancellation
  cmd/descheduler/app/server.go
  pkg/descheduler/descheduler.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#694 Updates to include annotations to the service account
  charts/descheduler/templates/serviceaccount.yaml
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#660 Adding 'affinity' support to run 'descheduler' in CronJob or Deployment
  charts/descheduler/templates/cronjob.yaml
  charts/descheduler/templates/deployment.yaml
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test
