Repository kubernetes-sigs/descheduler, pull requests merged in 2022-03, with the labels that each got.

#748 Update manifests and doc for v0.23.1
  docs/user-guide.md
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#740 fix doc about NPD description
  docs/user-guide.md
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#739 Share links to all descheduler ehnacements proposals in the project repo
  docs/proposals.md
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#745 [release-1.22] Bump Go to 1.16.14
  Dockerfile
  pkg/api/v1alpha1/zz_generated.conversion.go
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/api/v1alpha1/zz_generated.defaults.go
  pkg/api/zz_generated.deepcopy.go
  pkg/apis/componentconfig/v1alpha1/zz_generated.conversion.go
  pkg/apis/componentconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/componentconfig/v1alpha1/zz_generated.defaults.go
  pkg/apis/componentconfig/zz_generated.deepcopy.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#757 add conflicting taint to the logs
  pkg/utils/pod.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#758 Update docs for maxNoOfPodsToEvictPerNamespace
  README.md
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#760 [e2e] TestTooManyRestarts: check err and len before accessing pod items
  test/e2e/e2e_toomanyrestarts_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#761 [e2e] TestTooManyRestarts: check if container status is set before accessing
  test/e2e/e2e_toomanyrestarts_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#759 OWNERS: add janeliul as a reviewer
  OWNERS
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#764 RemovePodsViolatingNodeTaints: optionally include PreferNoSchedule taint
  pkg/api/types.go
  pkg/api/v1alpha1/types.go
  pkg/api/v1alpha1/zz_generated.conversion.go
  pkg/descheduler/strategies/node_taint.go
  pkg/descheduler/strategies/node_taint_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#762 Promote NodeUsage to NodeInfo, evaluate thresholds separately
  pkg/descheduler/strategies/nodeutilization/highnodeutilization.go
  pkg/descheduler/strategies/nodeutilization/lownodeutilization.go
  pkg/descheduler/strategies/nodeutilization/nodeutilization.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#777 Add RemovePodsViolatingNodeTaints taint exclusion
  README.md
  pkg/api/types.go
  pkg/api/v1alpha1/types.go
  pkg/api/v1alpha1/zz_generated.conversion.go
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/api/zz_generated.deepcopy.go
  pkg/descheduler/strategies/node_taint.go
  pkg/descheduler/strategies/node_taint_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#751 feat: Add DeviationThreshold Paramter for LowNodeUtilization, (Previous attempt - #473 )
  README.md
  pkg/api/types.go
  pkg/api/v1alpha1/types.go
  pkg/api/v1alpha1/zz_generated.conversion.go
  pkg/descheduler/strategies/nodeutilization/highnodeutilization.go
  pkg/descheduler/strategies/nodeutilization/lownodeutilization.go
  pkg/descheduler/strategies/nodeutilization/lownodeutilization_test.go
  pkg/descheduler/strategies/nodeutilization/nodeutilization.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#722 feat(leaderelection): impl leader election for HA Deployment
  README.md
  charts/descheduler/README.md
  charts/descheduler/templates/NOTES.txt
  charts/descheduler/templates/_helpers.tpl
  charts/descheduler/templates/clusterrole.yaml
  charts/descheduler/templates/deployment.yaml
  charts/descheduler/values.yaml
  cmd/descheduler/app/options/options.go
  docs/user-guide.md
  kubernetes/base/rbac.yaml
  pkg/apis/componentconfig/types.go
  pkg/apis/componentconfig/v1alpha1/types.go
  pkg/apis/componentconfig/v1alpha1/zz_generated.conversion.go
  pkg/apis/componentconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/componentconfig/zz_generated.deepcopy.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/leaderelection.go
  test/e2e/e2e_duplicatepods_test.go
  test/e2e/e2e_leaderelection_test.go
  test/e2e/e2e_test.go
  test/e2e/policy_leaderelection_a.yaml
  test/e2e/policy_leaderelection_b.yaml
  vendor/k8s.io/client-go/tools/leaderelection/OWNERS
  vendor/k8s.io/client-go/tools/leaderelection/healthzadaptor.go
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
  vendor/k8s.io/client-go/tools/leaderelection/metrics.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/interface.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/multilock.go
  vendor/k8s.io/component-base/config/options/leaderelectionconfig.go
  vendor/modules.txt
Labels: kind/feature, cncf-cla: yes, size/XXL, lgtm, approved, ok-to-test

#771 Sort nodes in ascending order for HighNodeUtilization
  pkg/descheduler/strategies/nodeutilization/highnodeutilization.go
  pkg/descheduler/strategies/nodeutilization/lownodeutilization.go
  pkg/descheduler/strategies/nodeutilization/nodeutilization.go
  pkg/descheduler/strategies/nodeutilization/nodeutilization_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test
