Repository kubernetes-sigs/descheduler, pull requests merged in 2022-11, with the labels that each got.

#853 add warning when enabling both dryRun and leaderElection
  charts/descheduler/templates/NOTES.txt
  charts/descheduler/values.yaml
  pkg/descheduler/descheduler.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#998 Switch to registry.k8s.io
  charts/descheduler/README.md
  charts/descheduler/values.yaml
  docs/user-guide.md
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved

#1000 add myself to reviewers
  OWNERS
Labels: cncf-cla: yes, size/XS, lgtm, approved

#969 run: `gofumpt -w -extra .`
  .golangci.yml
  Makefile
  cmd/descheduler/app/server.go
  cmd/descheduler/app/version.go
  docs/contributor-guide.md
  pkg/api/types.go
  pkg/api/v1alpha1/register.go
  pkg/api/v1alpha1/types.go
  pkg/apis/componentconfig/v1alpha1/register.go
  pkg/descheduler/client/client.go
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/evictions/evictions_test.go
  pkg/descheduler/leaderelection.go
  pkg/descheduler/node/node_test.go
  pkg/descheduler/strategies/validation/strategyparams_test.go
  pkg/framework/fake/fake.go
  pkg/framework/plugins/defaultevictor/defaultevictor_test.go
  pkg/framework/plugins/defaultevictor/defaults_test.go
  pkg/framework/plugins/nodeutilization/defaults_test.go
  pkg/framework/plugins/nodeutilization/highnodeutilization_test.go
  pkg/framework/plugins/nodeutilization/lownodeutilization_test.go
  pkg/framework/plugins/nodeutilization/nodeutilization.go
  pkg/framework/plugins/nodeutilization/validation.go
  pkg/framework/plugins/nodeutilization/validation_test.go
  pkg/framework/plugins/podlifetime/defaults_test.go
  pkg/framework/plugins/podlifetime/pod_lifetime_test.go
  pkg/framework/plugins/podlifetime/validation.go
  pkg/framework/plugins/podlifetime/validation_test.go
  pkg/framework/plugins/removeduplicates/defaults_test.go
  pkg/framework/plugins/removeduplicates/removeduplicates_test.go
  pkg/framework/plugins/removefailedpods/defaults_test.go
  pkg/framework/plugins/removefailedpods/failedpods_test.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/defaults_test.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts_test.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/validation.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/defaults_test.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity_test.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/validation.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/defaults_test.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity_test.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/validation.go
  pkg/framework/plugins/removepodsviolatingnodetaints/defaults_test.go
  pkg/framework/plugins/removepodsviolatingnodetaints/node_taint_test.go
  pkg/framework/plugins/removepodsviolatingnodetaints/validation.go
  pkg/framework/plugins/removepodsviolatingnodetaints/validation_test.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/defaults_test.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint_test.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/validation.go
  pkg/utils/pod.go
  test/e2e/e2e_duplicatepods_test.go
  test/e2e/e2e_failedpods_test.go
  test/e2e/e2e_test.go
  test/e2e/e2e_toomanyrestarts_test.go
  test/test_utils.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test
