Repository kubernetes-sigs/descheduler, pull requests merged in 2022-05, with the labels that each got.

#790 Added request considerations to NodeFit Feature [#636 follow up]
  README.md
  pkg/descheduler/descheduler.go
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/evictions/evictions_test.go
  pkg/descheduler/node/node.go
  pkg/descheduler/node/node_test.go
  pkg/descheduler/strategies/duplicates_test.go
  pkg/descheduler/strategies/failedpods_test.go
  pkg/descheduler/strategies/node_affinity.go
  pkg/descheduler/strategies/node_affinity_test.go
  pkg/descheduler/strategies/node_taint_test.go
  pkg/descheduler/strategies/nodeutilization/highnodeutilization.go
  pkg/descheduler/strategies/nodeutilization/highnodeutilization_test.go
  pkg/descheduler/strategies/nodeutilization/lownodeutilization.go
  pkg/descheduler/strategies/nodeutilization/lownodeutilization_test.go
  pkg/descheduler/strategies/nodeutilization/nodeutilization.go
  pkg/descheduler/strategies/pod_antiaffinity_test.go
  pkg/descheduler/strategies/pod_lifetime_test.go
  pkg/descheduler/strategies/toomanyrestarts_test.go
  pkg/descheduler/strategies/topologyspreadconstraint.go
  pkg/descheduler/strategies/topologyspreadconstraint_test.go
  pkg/utils/pod.go
  test/e2e/e2e_duplicatepods_test.go
  test/e2e/e2e_failedpods_test.go
  test/e2e/e2e_test.go
  test/e2e/e2e_toomanyrestarts_test.go
  test/e2e/e2e_topologyspreadconstraint_test.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#795 Update e2e test versions
  Makefile
  hack/verify-gofmt.sh
  pkg/descheduler/strategies/duplicates_test.go
  pkg/descheduler/strategies/nodeutilization/nodeutilization.go
  test/e2e/e2e_test.go
  test/run-e2e-tests.sh
Labels: cncf-cla: yes, size/S, lgtm, approved

#792 Update Docs and Manifests for v0.24.0
  README.md
  docs/user-guide.md
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#791 Bump to k8s 1.24.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: cncf-cla: yes, size/M, lgtm, approved

#796 Update helm chart version to v0.24
  charts/descheduler/Chart.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#801 Bump To Go 1.18.2
  Dockerfile
  go.mod
  go.sum
  hack/update-gofmt.sh
  hack/verify-gofmt.sh
Labels: cncf-cla: yes, size/S, lgtm, kind/cleanup, approved

#808 [release-1.24] Bump To Go 1.18.2
  Dockerfile
  go.mod
  go.sum
  hack/update-gofmt.sh
  hack/verify-gofmt.sh
Labels: cncf-cla: yes, size/S, lgtm, approved

#809 bump: golang.org/x/crypto
  go.mod
  go.sum
  vendor/golang.org/x/crypto/cryptobyte/builder.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_generic.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_s390x.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/S, lgtm, approved

#810 [release-1.24] bump: golang.org/x/crypto
  go.mod
  go.sum
  vendor/golang.org/x/crypto/cryptobyte/builder.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_generic.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_s390x.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/S, lgtm, approved

#813 Arguments must be strings, not bool or number
  charts/descheduler/templates/_helpers.tpl
  charts/descheduler/templates/clusterrole.yaml
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#817 [release-1.24] helm chart fixes
  charts/descheduler/README.md
  charts/descheduler/templates/_helpers.tpl
  charts/descheduler/templates/clusterrole.yaml
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved

#818 Update release guide docs
  docs/release-guide.md
  docs/release-process.png
Labels: cncf-cla: yes, size/L, lgtm, approved

#820 [release-1.24] Update helm chart for v0.24.1
  README.md
  charts/descheduler/Chart.yaml
  docs/user-guide.md
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#821 Update helm tests util versions and release guide
  docs/release-guide.md
  test/run-helm-tests.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test
