Repository kubernetes-sigs/descheduler, pull requests merged in 2022-06, with the labels that each got.

#824 [release-1.24] Fix version command to parse helm chart tags
  Makefile
  cloudbuild.yaml
  pkg/version/version.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#805 cleanup lownodeutilization code
  pkg/descheduler/strategies/nodeutilization/lownodeutilization.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#830 Revert "cleanup lownodeutilization code"
  pkg/descheduler/strategies/nodeutilization/lownodeutilization.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#833 PodLifeTime: sort pods by creation timestamp
  go.mod
  pkg/descheduler/pod/pods.go
  pkg/descheduler/pod/pods_test.go
  pkg/descheduler/strategies/pod_lifetime.go
  pkg/descheduler/strategies/pod_lifetime_test.go
  test/e2e/e2e_duplicatepods_test.go
  test/e2e/e2e_failedpods_test.go
  test/e2e/e2e_leaderelection_test.go
  test/e2e/e2e_test.go
  test/e2e/e2e_toomanyrestarts_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#843 Update docs, manifests for 0.24.1 on master
  README.md
  charts/descheduler/Chart.yaml
  docs/user-guide.md
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#852 Check existing constraints before assigning
  pkg/descheduler/strategies/topologyspreadconstraint.go
  pkg/descheduler/strategies/topologyspreadconstraint_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#856 remove random creation timestamp from pod sort by age test
  pkg/descheduler/pod/pods_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#847 Split pod evictor and evictor filter
  pkg/descheduler/descheduler.go
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/evictions/evictions_test.go
  pkg/descheduler/strategies/duplicates.go
  pkg/descheduler/strategies/duplicates_test.go
  pkg/descheduler/strategies/failedpods.go
  pkg/descheduler/strategies/failedpods_test.go
  pkg/descheduler/strategies/node_affinity.go
  pkg/descheduler/strategies/node_affinity_test.go
  pkg/descheduler/strategies/node_taint.go
  pkg/descheduler/strategies/node_taint_test.go
  pkg/descheduler/strategies/nodeutilization/highnodeutilization.go
  pkg/descheduler/strategies/nodeutilization/highnodeutilization_test.go
  pkg/descheduler/strategies/nodeutilization/lownodeutilization.go
  pkg/descheduler/strategies/nodeutilization/lownodeutilization_test.go
  pkg/descheduler/strategies/pod_antiaffinity.go
  pkg/descheduler/strategies/pod_antiaffinity_test.go
  pkg/descheduler/strategies/pod_lifetime.go
  pkg/descheduler/strategies/pod_lifetime_test.go
  pkg/descheduler/strategies/toomanyrestarts.go
  pkg/descheduler/strategies/toomanyrestarts_test.go
  pkg/descheduler/strategies/topologyspreadconstraint.go
  pkg/descheduler/strategies/topologyspreadconstraint_test.go
  test/e2e/e2e_duplicatepods_test.go
  test/e2e/e2e_failedpods_test.go
  test/e2e/e2e_test.go
  test/e2e/e2e_toomanyrestarts_test.go
  test/e2e/e2e_topologyspreadconstraint_test.go
Labels: cncf-cla: yes, size/XL, lgtm, approved, ok-to-test

#834 PodLifeTime: support container states PodInitializing and ContainerCreating
  README.md
  examples/pod-life-time.yml
  pkg/api/types.go
  pkg/api/v1alpha1/types.go
  pkg/api/v1alpha1/zz_generated.conversion.go
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/api/zz_generated.deepcopy.go
  pkg/descheduler/strategies/pod_lifetime.go
  pkg/descheduler/strategies/pod_lifetime_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved
