Repository kubernetes-sigs/descheduler, pull requests merged in 2022-09, with the labels that each got.

#938 remove dependency on kubectl
  go.mod
  go.sum
  test/e2e/e2e_test.go
  vendor/k8s.io/kubectl/LICENSE
  vendor/k8s.io/kubectl/pkg/util/qos/qos.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/L, lgtm, approved

#943 Add RemovePodsViolatingTopologySpreadConstraint to values.yaml
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#928 clarify which version PodLifeTime introduced states parameter and deprecated podStatusPhases
  README.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#945 feat: add RemovePodsHavingTooManyRestarts to values.yaml
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#935 Update docs & manifests for v0.25.0
  README.md
  docs/user-guide.md
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#931 remove TODO comments for cronjob v1beta1 support
  charts/descheduler/values.yaml
  kubernetes/cronjob/cronjob.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#929 Add new DefaultEvictor plugin with args
  hack/update-generated-deep-copies.sh
  hack/verify-deep-copies.sh
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/evictions/evictions_test.go
  pkg/framework/fake/fake.go
  pkg/framework/plugins/defaultevictor/defaultevictor.go
  pkg/framework/plugins/defaultevictor/defaultevictor_test.go
  pkg/framework/plugins/defaultevictor/types.go
  pkg/framework/plugins/defaultevictor/zz_generated.deepcopy.go
  pkg/framework/plugins/nodeutilization/highnodeutilization_test.go
  pkg/framework/plugins/nodeutilization/lownodeutilization_test.go
  pkg/framework/plugins/podlifetime/pod_lifetime_test.go
  pkg/framework/plugins/removeduplicates/removeduplicates_test.go
  pkg/framework/plugins/removefailedpods/failedpods_test.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts_test.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity_test.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity_test.go
  pkg/framework/plugins/removepodsviolatingnodetaints/node_taint_test.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint_test.go
  pkg/framework/types.go
  pkg/utils/priority.go
  test/e2e/e2e_duplicatepods_test.go
  test/e2e/e2e_failedpods_test.go
  test/e2e/e2e_test.go
  test/e2e/e2e_toomanyrestarts_test.go
  test/e2e/e2e_topologyspreadconstraint_test.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#947 feat: change DeschedulerVersion and GitVersion labels
  metrics/metrics.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#952 Fix wrong command on contributor-guide.md
  docs/contributor-guide.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#955 add PreEvictionFilter extension to DefaultEvictor Plugin
  pkg/descheduler/descheduler.go
  pkg/framework/fake/fake.go
  pkg/framework/plugins/defaultevictor/defaultevictor.go
  pkg/framework/plugins/defaultevictor/defaultevictor_test.go
  pkg/framework/plugins/nodeutilization/nodeutilization.go
  pkg/framework/plugins/podlifetime/pod_lifetime.go
  pkg/framework/plugins/removeduplicates/removeduplicates.go
  pkg/framework/plugins/removefailedpods/failedpods.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity.go
  pkg/framework/plugins/removepodsviolatingnodetaints/node_taint.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint.go
  pkg/framework/types.go
Labels: cncf-cla: yes, size/XL, lgtm, approved

#957 feat: show nodename in evicted events
  pkg/descheduler/evictions/evictions.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#956 fix sharedInformerFactory register
  pkg/descheduler/descheduler.go
  pkg/descheduler/node/node.go
  pkg/descheduler/node/node_test.go
  pkg/descheduler/pod/pods.go
  pkg/descheduler/pod/pods_test.go
  pkg/framework/plugins/defaultevictor/defaultevictor.go
  pkg/framework/plugins/defaultevictor/defaultevictor_test.go
  pkg/framework/plugins/nodeutilization/highnodeutilization_test.go
  pkg/framework/plugins/nodeutilization/lownodeutilization_test.go
  pkg/framework/plugins/podlifetime/pod_lifetime_test.go
  pkg/framework/plugins/removeduplicates/removeduplicates_test.go
  pkg/framework/plugins/removefailedpods/failedpods_test.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts_test.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity_test.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity_test.go
  pkg/framework/plugins/removepodsviolatingnodetaints/node_taint_test.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint_test.go
  test/e2e/e2e_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#961 includeSoftConstraints not being respected for TopologySpreadConstraint
  pkg/descheduler/strategy_migration.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#962 backport 7349b39 (issue 960) into release-1.25
  pkg/descheduler/strategy_migration.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#963 [release-1.25] Doc updates for v0.25.1
  README.md
  docs/user-guide.md
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#964 Update Helm chart to v0.25.1
  charts/descheduler/Chart.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#953 set helm-extra-set-args as inline command arg
  .github/ci/ct.yaml
  .github/workflows/helm.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved
