Repository kubernetes-sigs/descheduler, pull requests merged in 2022-12, with the labels that each got.

#1003 use plugin registry and prepare for conversion
  cmd/descheduler/app/server.go
  cmd/descheduler/descheduler.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/descheduler_test.go
  pkg/descheduler/policyconfig.go
  pkg/descheduler/policyconfig_test.go
  pkg/descheduler/setupplugins.go
  pkg/descheduler/strategy_migration.go
  pkg/framework/plugins/defaultevictor/defaultevictor.go
  pkg/framework/plugins/defaultevictor/types.go
  pkg/framework/plugins/defaultevictor/zz_generated.deepcopy.go
  pkg/framework/plugins/nodeutilization/types.go
  pkg/framework/plugins/pluginbuilder/pluginbuilder.go
  pkg/framework/plugins/podlifetime/types.go
  pkg/framework/plugins/removeduplicates/types.go
  pkg/framework/plugins/removefailedpods/types.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/types.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/types.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/types.go
  pkg/framework/plugins/removepodsviolatingnodetaints/types.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/types.go
  test/e2e/e2e_leaderelection_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, tide/merge-method-squash

#1016 logo in readme
  README.md
  assets/logo/descheduler-stacked-color.png
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1022 Allow a setting option `ttlSecondsAfterFinished` for job
  charts/descheduler/README.md
  charts/descheduler/templates/cronjob.yaml
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#1019 parallelize docker build for each arch
  Makefile
  cloudbuild.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved

#1018 update version references in docs and readme
  .github/workflows/helm.yaml
  README.md
  test/run-e2e-tests.sh
Labels: cncf-cla: yes, size/S, lgtm, approved

#1023 increase cloudbuild timeout to 30 minutes until we figure out proper optimizations
  cloudbuild.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1028 Increase cloud build timeout to 1 hour
  cloudbuild.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1030 cleanup: remove ioutil for new go version
  pkg/descheduler/policyconfig.go
Labels: cncf-cla: yes, size/XS, lgtm, kind/cleanup, approved, ok-to-test
