Repository kubernetes-sigs/descheduler, pull requests merged in 2022-08, with the labels that each got.

#888 fix: events memory leak. Using new events implementation and take recorder out of EvictPod
  cmd/descheduler/app/options/options.go
  kubernetes/base/rbac.yaml
  pkg/descheduler/client/client.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/descheduler_test.go
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/strategies/duplicates_test.go
  pkg/descheduler/strategies/failedpods_test.go
  pkg/descheduler/strategies/node_affinity_test.go
  pkg/descheduler/strategies/nodeutilization/highnodeutilization_test.go
  pkg/descheduler/strategies/nodeutilization/lownodeutilization_test.go
  pkg/descheduler/strategies/pod_antiaffinity_test.go
  pkg/descheduler/strategies/pod_lifetime_test.go
  pkg/descheduler/strategies/toomanyrestarts_test.go
  pkg/descheduler/strategies/topologyspreadconstraint_test.go
  pkg/framework/plugins/removepodsviolatingnodetaints/node_taint_test.go
  pkg/utils/events.go
  test/e2e/e2e_duplicatepods_test.go
  test/e2e/e2e_test.go
  test/e2e/e2e_toomanyrestarts_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#896 Remove emeritus_approvers from reviewers
  OWNERS
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#861 Migrate RemoveFailedPods to plugin
  pkg/apis/componentconfig/types_pluginargs.go
  pkg/apis/componentconfig/validation/validation_pluginargs.go
  pkg/apis/componentconfig/zz_generated.deepcopy.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/strategies/failedpods.go
  pkg/descheduler/strategy_migration.go
  pkg/framework/plugins/removefailedpods/failedpods.go
  pkg/framework/plugins/removefailedpods/failedpods_test.go
  test/e2e/e2e_duplicatepods_test.go
  test/e2e/e2e_failedpods_test.go
  test/e2e/e2e_leaderelection_test.go
  test/e2e/e2e_test.go
  test/e2e/e2e_toomanyrestarts_test.go
  test/e2e/e2e_topologyspreadconstraint_test.go
Labels: cncf-cla: yes, size/XL, lgtm, approved

#904 add helm ct install.
  .github/ci/ct.yaml
  .github/workflows/helm.yaml
  Makefile
  docs/contributor-guide.md
  test/run-e2e-tests.sh
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#860 Migrate RemovePodsViolatingNodeAffinity to plugin
  pkg/apis/componentconfig/types_pluginargs.go
  pkg/apis/componentconfig/validation/validation_pluginargs.go
  pkg/apis/componentconfig/zz_generated.deepcopy.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/strategies/node_affinity.go
  pkg/descheduler/strategy_migration.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#902 Migrate RemovePodsHavingTooManyRestarts to plugin
  pkg/apis/componentconfig/types_pluginargs.go
  pkg/apis/componentconfig/validation/validation_pluginargs.go
  pkg/apis/componentconfig/zz_generated.deepcopy.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/strategies/toomanyrestarts.go
  pkg/descheduler/strategy_migration.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts_test.go
  test/e2e/e2e_toomanyrestarts_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#906 NodeAffinity plugin to use the existing validation methods
  pkg/apis/componentconfig/types_pluginargs.go
  pkg/apis/componentconfig/validation/validation_pluginargs.go
  pkg/apis/componentconfig/validation/validation_pluginargs_test.go
  pkg/framework/plugins/removefailedpods/failedpods.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#892 bring removeduplicates to plugin
  pkg/apis/componentconfig/types_pluginargs.go
  pkg/apis/componentconfig/validation/validation_pluginargs.go
  pkg/apis/componentconfig/zz_generated.deepcopy.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/strategy_migration.go
  pkg/framework/plugins/removeduplicates/removeduplicates.go
  pkg/framework/plugins/removeduplicates/removeduplicates_test.go
  test/e2e/e2e_duplicatepods_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#911 introduce ct for local helm install test
  .github/workflows/helm.yaml
  Makefile
  charts/descheduler/templates/tests/test-descheduler-pod.yaml
  docs/contributor-guide.md
  hack/verify-chart.sh
  test/run-helm-tests.sh
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#912 CONTAINER_ENGINE to override the default docker engine
  Makefile
  hack/verify-chart.sh
  test/run-e2e-tests.sh
Labels: cncf-cla: yes, size/M, lgtm, approved

#913 Migrate PodLifeTime to plugin
  pkg/apis/componentconfig/types_pluginargs.go
  pkg/apis/componentconfig/validation/validation_pluginargs.go
  pkg/apis/componentconfig/validation/validation_pluginargs_test.go
  pkg/apis/componentconfig/zz_generated.deepcopy.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/strategies/pod_lifetime.go
  pkg/descheduler/strategy_migration.go
  pkg/framework/plugins/podlifetime/pod_lifetime.go
  pkg/framework/plugins/podlifetime/pod_lifetime_test.go
  test/e2e/e2e_test.go
Labels: cncf-cla: yes, size/XL, lgtm, approved

#908 RemovePodsViolatingTopologySpreadConstraint Plugin
  pkg/apis/componentconfig/types_pluginargs.go
  pkg/apis/componentconfig/validation/validation_pluginargs.go
  pkg/apis/componentconfig/zz_generated.deepcopy.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/strategy_migration.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint_test.go
  test/e2e/e2e_topologyspreadconstraint_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#898 add security scan into gh-actions
  .github/workflows/security.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#916 NodeFit: do not check whether node fitsRequest when a pod is already assigned to the node
  pkg/descheduler/node/node.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#903 Migrate RemovePodsViolatingInterPodAntiAffinity into a plugin
  pkg/api/types.go
  pkg/apis/componentconfig/types_pluginargs.go
  pkg/apis/componentconfig/validation/validation_pluginargs.go
  pkg/apis/componentconfig/zz_generated.deepcopy.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/strategy_migration.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#910 bring lownodeutilization and highnodeutilization to plugin
  pkg/apis/componentconfig/types_pluginargs.go
  pkg/apis/componentconfig/validation/validation_pluginargs.go
  pkg/apis/componentconfig/validation/validation_pluginargs_test.go
  pkg/apis/componentconfig/zz_generated.deepcopy.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/strategy_migration.go
  pkg/framework/plugins/nodeutilization/highnodeutilization.go
  pkg/framework/plugins/nodeutilization/highnodeutilization_test.go
  pkg/framework/plugins/nodeutilization/lownodeutilization.go
  pkg/framework/plugins/nodeutilization/lownodeutilization_test.go
  pkg/framework/plugins/nodeutilization/nodeutilization.go
  pkg/framework/plugins/nodeutilization/nodeutilization_test.go
  test/e2e/e2e_test.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#922 removing dupe plugin interface check
  pkg/framework/plugins/nodeutilization/highnodeutilization.go
  pkg/framework/plugins/nodeutilization/lownodeutilization.go
  pkg/framework/plugins/podlifetime/pod_lifetime.go
  pkg/framework/plugins/removeduplicates/removeduplicates.go
  pkg/framework/plugins/removefailedpods/failedpods.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity.go
  pkg/framework/plugins/removepodsviolatingnodetaints/node_taint.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test
