Repository kubernetes-sigs/descheduler, pull requests merged in 2022-02, with the labels that each got.

#709 Update helm chart version to v0.23
  charts/descheduler/Chart.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#710 [release-1.23] Update helm chart version to v0.23
  charts/descheduler/Chart.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#712 fix helmchart fail to watch namespace issue
  charts/descheduler/templates/clusterrole.yaml
  kubernetes/base/rbac.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#717 [release-1.23.1] Update helm chart version to v0.23.1
  charts/descheduler/Chart.yaml
  docs/user-guide.md
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#697 OWNERS: add a7i as a reviewer
  OWNERS
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#716 fix: add imagePullSecrets for deployment resource
  charts/descheduler/templates/deployment.yaml
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#726 Eviction Logs
  pkg/descheduler/evictions/evictions.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#715 fix: Remove deprecated parameters from cmdOptions and add the parameters under policy
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#708 Clarify resource calculations in NodeUtilization strategy Readmes
  README.md
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/documentation

#731 Bugfix: Cronjob ctx cancel
  cmd/descheduler/app/server.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/descheduler_test.go
  test/e2e/e2e_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#733 remove MostRequestedPriority from doc since already deprecated
  README.md
  docs/user-guide.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#744 Update golang image
  Dockerfile
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#742 [release-1.23] Backport context cancel panic + Go version update
  Dockerfile
  charts/descheduler/Chart.yaml
  cmd/descheduler/app/server.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/descheduler_test.go
  test/e2e/e2e_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#747 [release-1.23] Update manifests and doc for v0.23.1
  docs/user-guide.md
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved
