Repository kubernetes-sigs/descheduler, pull requests merged in 2022-10, with the labels that each got.

#973 📖 Fix broken kustomize reference in the root README
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#987 README: be more explicit about scope of the descheduler.alpha.kubernetes.io/evict annotation
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#989 [release-1.25] Update helm chart rolebinding to use events.k8s.io
  charts/descheduler/Chart.yaml
  charts/descheduler/templates/clusterrole.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#975 add restricted security policy to e2e test pods
  test/e2e/e2e_duplicatepods_test.go
  test/e2e/e2e_leaderelection_test.go
  test/e2e/e2e_test.go
  test/e2e/e2e_toomanyrestarts_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#982 Update verify scripts to use the generation scripts directly
  hack/verify-conversions.sh
  hack/verify-deep-copies.sh
  hack/verify-defaulters.sh
Labels: cncf-cla: yes, size/S, lgtm, approved

#990 Update helm chart rolebinding to use events.k8s.io
  charts/descheduler/templates/clusterrole.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#993 correct JSON log format
  cmd/descheduler/app/server.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#967 add namespace filter to nodeutilization
  README.md
  pkg/framework/plugins/nodeutilization/highnodeutilization.go
  pkg/framework/plugins/nodeutilization/lownodeutilization.go
  pkg/framework/plugins/nodeutilization/lownodeutilization_test.go
  pkg/framework/plugins/nodeutilization/nodeutilization.go
  pkg/framework/plugins/nodeutilization/types.go
  pkg/framework/plugins/nodeutilization/validation.go
  pkg/framework/plugins/nodeutilization/zz_generated.deepcopy.go
Labels: cncf-cla: yes, size/L, lgtm, approved
