Repository kubernetes-sigs/descheduler, pull requests merged in 2023-01, with the labels that each got.

#1035 update license year boilerplate by running make gen
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/api/v1alpha1/zz_generated.defaults.go
  pkg/api/zz_generated.deepcopy.go
  pkg/apis/componentconfig/v1alpha1/zz_generated.conversion.go
  pkg/apis/componentconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/componentconfig/v1alpha1/zz_generated.defaults.go
  pkg/apis/componentconfig/zz_generated.deepcopy.go
  pkg/framework/plugins/defaultevictor/zz_generated.deepcopy.go
  pkg/framework/plugins/defaultevictor/zz_generated.defaults.go
  pkg/framework/plugins/nodeutilization/zz_generated.deepcopy.go
  pkg/framework/plugins/nodeutilization/zz_generated.defaults.go
  pkg/framework/plugins/podlifetime/zz_generated.deepcopy.go
  pkg/framework/plugins/podlifetime/zz_generated.defaults.go
  pkg/framework/plugins/removeduplicates/zz_generated.deepcopy.go
  pkg/framework/plugins/removeduplicates/zz_generated.defaults.go
  pkg/framework/plugins/removefailedpods/zz_generated.deepcopy.go
  pkg/framework/plugins/removefailedpods/zz_generated.defaults.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/zz_generated.deepcopy.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/zz_generated.defaults.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/zz_generated.deepcopy.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/zz_generated.defaults.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/zz_generated.deepcopy.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/zz_generated.defaults.go
  pkg/framework/plugins/removepodsviolatingnodetaints/zz_generated.deepcopy.go
  pkg/framework/plugins/removepodsviolatingnodetaints/zz_generated.defaults.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/zz_generated.deepcopy.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/zz_generated.defaults.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#995 Split CMD into ENTRYPOINT and CMD for Dockerfile
  Dockerfile
  Dockerfile.dev
  charts/descheduler/templates/cronjob.yaml
  charts/descheduler/templates/deployment.yaml
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1042 Revert "Split CMD into ENTRYPOINT and CMD for Dockerfile"
  Dockerfile
  Dockerfile.dev
  charts/descheduler/templates/cronjob.yaml
  charts/descheduler/templates/deployment.yaml
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1038 Update helm chart to v0.26.0
  charts/descheduler/Chart.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1034 support client connection configuration to provide QPS and burst
  cmd/descheduler/app/options/options.go
  docs/contributor-guide.md
  docs/user-guide.md
  pkg/apis/componentconfig/types.go
  pkg/apis/componentconfig/v1alpha1/types.go
  pkg/apis/componentconfig/v1alpha1/zz_generated.conversion.go
  pkg/apis/componentconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/componentconfig/zz_generated.deepcopy.go
  pkg/descheduler/client/client.go
  pkg/descheduler/descheduler.go
  test/e2e/e2e_leaderelection_test.go
  test/e2e/e2e_test.go
  test/e2e/test_clientconnection_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1048 enable auto generation of the documents
  Makefile
  docs/cli/descheduler.md
  docs/cli/descheduler_version.md
  docs/user-guide.md
  go.mod
  go.sum
  hack/doc-gen/main.go
  hack/update-docs.sh
  hack/verify-docs.sh
  vendor/github.com/cpuguy83/go-md2man/v2/LICENSE.md
  vendor/github.com/cpuguy83/go-md2man/v2/md2man/md2man.go
  vendor/github.com/cpuguy83/go-md2man/v2/md2man/roff.go
  vendor/github.com/russross/blackfriday/v2/.gitignore
  vendor/github.com/russross/blackfriday/v2/.travis.yml
  vendor/github.com/russross/blackfriday/v2/LICENSE.txt
  vendor/github.com/russross/blackfriday/v2/README.md
  vendor/github.com/russross/blackfriday/v2/block.go
  vendor/github.com/russross/blackfriday/v2/doc.go
  vendor/github.com/russross/blackfriday/v2/entities.go
  vendor/github.com/russross/blackfriday/v2/esc.go
  vendor/github.com/russross/blackfriday/v2/html.go
  vendor/github.com/russross/blackfriday/v2/inline.go
  vendor/github.com/russross/blackfriday/v2/markdown.go
  vendor/github.com/russross/blackfriday/v2/node.go
  vendor/github.com/russross/blackfriday/v2/smartypants.go
  vendor/github.com/spf13/cobra/doc/README.md
  vendor/github.com/spf13/cobra/doc/man_docs.go
  vendor/github.com/spf13/cobra/doc/man_docs.md
  vendor/github.com/spf13/cobra/doc/md_docs.go
  vendor/github.com/spf13/cobra/doc/md_docs.md
  vendor/github.com/spf13/cobra/doc/rest_docs.go
  vendor/github.com/spf13/cobra/doc/rest_docs.md
  vendor/github.com/spf13/cobra/doc/util.go
  vendor/github.com/spf13/cobra/doc/yaml_docs.go
  vendor/github.com/spf13/cobra/doc/yaml_docs.md
  vendor/modules.txt
Labels: cncf-cla: yes, size/XXL, lgtm, approved
