Repository kubernetes-sigs/descheduler, pull requests merged in 2023-08, with the labels that each got.

#1210 feat: Implement preferredDuringSchedulingIgnoredDuringExecution for RemovePodsViolatingNodeAffinity
  README.md
  pkg/descheduler/node/node.go
  pkg/descheduler/node/node_test.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity_test.go
  pkg/utils/pod.go
  pkg/utils/predicates.go
  pkg/utils/predicates_test.go
Labels: cncf-cla: yes, size/XL, lgtm, approved, tide/merge-method-squash, ok-to-test

#1215 fix: descheduler_loop_duration_seconds has wrong value
  pkg/descheduler/descheduler.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1221 profile: fix span attribute typo
  pkg/framework/profile/profile.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1224 k8s 1.28: update docs and go-version
  .github/workflows/helm.yaml
  .github/workflows/manifests.yaml
  Dockerfile
  Makefile
  README.md
  docs/deprecated/v1alpha1.md
  docs/user-guide.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#1225 helm: bump chart to v0.28.0
  .github/workflows/manifests.yaml
  charts/descheduler/Chart.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1228 fix: structured err logs in eviction
  pkg/descheduler/evictions/evictions.go
  pkg/framework/plugins/defaultevictor/defaultevictor.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1229 helm: update cronjob args argument to avoid unmarshal error
  charts/descheduler/templates/cronjob.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1231 helm: update cronjob args argument to avoid unmarshal error
  charts/descheduler/templates/cronjob.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved
