Repository kubernetes-sigs/descheduler, pull requests merged in 2023-05, with the labels that each got.

#1135 fix policy example configmap
  kubernetes/base/configmap.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1116 k8s 1.27: update docs and README
  README.md
  docs/deprecated/v1alpha1.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1136 update helm chart to v0.27.0
  README.md
  charts/descheduler/Chart.yaml
  docs/user-guide.md
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, tide/merge-method-squash

#1096 add unit tests for version compatibility check
  pkg/descheduler/descheduler.go
  pkg/descheduler/descheduler_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#1145 Use dl.k8s.io instead of kubernetes-release bucket
  test/run-e2e-tests.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1151 helm: ability to override command and args. set args inline
  charts/descheduler/templates/cronjob.yaml
  charts/descheduler/templates/deployment.yaml
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1150 fix: imagepullsecrets indentation for kind: Deployment
  charts/descheduler/templates/deployment.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1158 fix plugin arg conversion when using multiple profiles with same plugin
  pkg/api/v1alpha2/conversion.go
  pkg/descheduler/policyconfig.go
  pkg/descheduler/policyconfig_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#1159 docs: supplement missing link
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1160 bump chart to v0.27.1
  .github/workflows/manifests.yaml
  charts/descheduler/Chart.yaml
  docs/deprecated/v1alpha1.md
  docs/user-guide.md
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1147 Custom labels for ServiceMonitor resource
  charts/descheduler/README.md
  charts/descheduler/templates/servicemonitor.yaml
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, tide/merge-method-squash, ok-to-test
