Repository kubernetes-sigs/descheduler, pull requests merged in 2023-11, with the labels that each got.

#1281 fix: display ownerKey in the logs correctly
  pkg/framework/plugins/removeduplicates/removeduplicates.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1249 fix: version skew compatibility for managed kubernetes providers
  pkg/descheduler/descheduler.go
  pkg/descheduler/descheduler_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#1276 adding jklaw90 to reviewers
  OWNERS
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1282 copy cherry_pick_pull script form kubernetes/kubernetes
  hack/cherry_pick_pull.sh
Labels: cncf-cla: yes, size/L, lgtm, approved

#1296 fix: json logging
  cmd/descheduler/app/options/options.go
  cmd/descheduler/app/server.go
  cmd/descheduler/descheduler.go
  docs/cli/descheduler.md
  pkg/apis/componentconfig/types.go
  pkg/apis/componentconfig/v1alpha1/types.go
  pkg/apis/componentconfig/v1alpha1/zz_generated.conversion.go
  pkg/apis/componentconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/componentconfig/zz_generated.deepcopy.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#1294 Make the logged nodeutilization percentages human-readable
  pkg/framework/plugins/nodeutilization/nodeutilization.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, tide/merge-method-squash, ok-to-test

#1299 fix: revert defer of context done
  cmd/descheduler/app/server.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1292 chore: upgrade libs to kubernetes 0.28.4 and matching go version
  go.mod
  go.sum
  vendor/github.com/cpuguy83/go-md2man/v2/md2man/md2man.go
  vendor/github.com/cpuguy83/go-md2man/v2/md2man/roff.go
  vendor/github.com/go-logr/logr/slogr/sloghandler.go
  vendor/github.com/go-logr/logr/slogr/slogr.go
  vendor/github.com/go-logr/logr/slogr/slogsink.go
  vendor/github.com/spf13/cobra/.golangci.yml
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/active_help.go
  vendor/github.com/spf13/cobra/active_help.md
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/bash_completionsV2.go
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/completions.go
  vendor/github.com/spf13/cobra/doc/README.md
  vendor/github.com/spf13/cobra/doc/man_docs.md
  vendor/github.com/spf13/cobra/doc/md_docs.go
  vendor/github.com/spf13/cobra/doc/md_docs.md
  vendor/github.com/spf13/cobra/doc/rest_docs.md
  vendor/github.com/spf13/cobra/doc/yaml_docs.md
  vendor/github.com/spf13/cobra/fish_completions.go
  vendor/github.com/spf13/cobra/fish_completions.md
  vendor/github.com/spf13/cobra/flag_groups.go
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/github.com/spf13/cobra/powershell_completions.md
  vendor/github.com/spf13/cobra/projects_using_cobra.md
  vendor/github.com/spf13/cobra/shell_completions.md
  vendor/github.com/spf13/cobra/user_guide.md
  vendor/github.com/spf13/cobra/zsh_completions.md
  vendor/k8s.io/klog/v2/.golangci.yaml
  vendor/k8s.io/klog/v2/internal/buffer/buffer.go
  vendor/k8s.io/klog/v2/internal/clock/clock.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues_no_slog.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues_slog.go
  vendor/k8s.io/klog/v2/internal/sloghandler/sloghandler_slog.go
  vendor/k8s.io/klog/v2/k8s_references_slog.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/k8s.io/klog/v2/klogr_slog.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/ptr/OWNERS
  vendor/k8s.io/utils/ptr/README.md
  vendor/k8s.io/utils/ptr/ptr.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#1302 Automated cherry pick of #1292: chore: upgrade libs to kubernetes 0.28.4 and matching go
  go.mod
  go.sum
  vendor/github.com/cpuguy83/go-md2man/v2/md2man/md2man.go
  vendor/github.com/cpuguy83/go-md2man/v2/md2man/roff.go
  vendor/github.com/go-logr/logr/slogr/sloghandler.go
  vendor/github.com/go-logr/logr/slogr/slogr.go
  vendor/github.com/go-logr/logr/slogr/slogsink.go
  vendor/github.com/spf13/cobra/.golangci.yml
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/active_help.go
  vendor/github.com/spf13/cobra/active_help.md
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/bash_completionsV2.go
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/completions.go
  vendor/github.com/spf13/cobra/doc/README.md
  vendor/github.com/spf13/cobra/doc/man_docs.md
  vendor/github.com/spf13/cobra/doc/md_docs.go
  vendor/github.com/spf13/cobra/doc/md_docs.md
  vendor/github.com/spf13/cobra/doc/rest_docs.md
  vendor/github.com/spf13/cobra/doc/yaml_docs.md
  vendor/github.com/spf13/cobra/fish_completions.go
  vendor/github.com/spf13/cobra/fish_completions.md
  vendor/github.com/spf13/cobra/flag_groups.go
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/github.com/spf13/cobra/powershell_completions.md
  vendor/github.com/spf13/cobra/projects_using_cobra.md
  vendor/github.com/spf13/cobra/shell_completions.md
  vendor/github.com/spf13/cobra/user_guide.md
  vendor/github.com/spf13/cobra/zsh_completions.md
  vendor/k8s.io/klog/v2/.golangci.yaml
  vendor/k8s.io/klog/v2/internal/buffer/buffer.go
  vendor/k8s.io/klog/v2/internal/clock/clock.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues_no_slog.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues_slog.go
  vendor/k8s.io/klog/v2/internal/sloghandler/sloghandler_slog.go
  vendor/k8s.io/klog/v2/k8s_references_slog.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/k8s.io/klog/v2/klogr_slog.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/ptr/OWNERS
  vendor/k8s.io/utils/ptr/README.md
  vendor/k8s.io/utils/ptr/ptr.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#1304 release v0.28.1: bump helm chart and images
  .github/workflows/manifests.yaml
  charts/descheduler/Chart.yaml
  docs/deprecated/v1alpha1.md
  docs/user-guide.md
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1305 release v0.28.1: bump helm chart and images
  .github/workflows/manifests.yaml
  charts/descheduler/Chart.yaml
  docs/deprecated/v1alpha1.md
  docs/user-guide.md
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1308 update helm icon to force release of v0.28.1
  charts/descheduler/Chart.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved
