Repository kubernetes-sigs/descheduler, pull requests merged in 2023-04, with the labels that each got.

#1103 dry-run cli flag to use uppercase
  cmd/descheduler/app/options/options.go
  docs/cli/descheduler.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1104 fix default value assignment of EvictLocalStoragePods
  pkg/framework/plugins/defaultevictor/defaults.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1106 fix default value assignment of EvictLocalStoragePods
  pkg/framework/plugins/defaultevictor/defaults.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1097 Populate extension points automatically for deschedule, balance, filter and preEvictionFilter
  pkg/api/v1alpha1/conversion.go
  pkg/descheduler/descheduler_test.go
  pkg/descheduler/setupplugins.go
  pkg/framework/fake/fake.go
  pkg/framework/fake/plugin/fake.go
  pkg/framework/fake/plugin/fixture.go
  pkg/framework/fake/plugin/zz_generated.deepcopy.go
  pkg/framework/pluginregistry/pluginregistry.go
  pkg/framework/plugins/defaultevictor/defaultevictor.go
  pkg/framework/plugins/defaultevictor/defaultevictor_test.go
  pkg/framework/plugins/nodeutilization/highnodeutilization.go
  pkg/framework/plugins/nodeutilization/highnodeutilization_test.go
  pkg/framework/plugins/nodeutilization/lownodeutilization.go
  pkg/framework/plugins/nodeutilization/lownodeutilization_test.go
  pkg/framework/plugins/nodeutilization/nodeutilization.go
  pkg/framework/plugins/podlifetime/pod_lifetime.go
  pkg/framework/plugins/podlifetime/pod_lifetime_test.go
  pkg/framework/plugins/removeduplicates/removeduplicates.go
  pkg/framework/plugins/removeduplicates/removeduplicates_test.go
  pkg/framework/plugins/removefailedpods/failedpods.go
  pkg/framework/plugins/removefailedpods/failedpods_test.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts_test.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity_test.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity_test.go
  pkg/framework/plugins/removepodsviolatingnodetaints/node_taint.go
  pkg/framework/plugins/removepodsviolatingnodetaints/node_taint_test.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint_test.go
  pkg/framework/profile/profile.go
  pkg/framework/profile/profile_test.go
  pkg/framework/types/types.go
  test/e2e/e2e_duplicatepods_test.go
  test/e2e/e2e_failedpods_test.go
  test/e2e/e2e_test.go
  test/e2e/e2e_toomanyrestarts_test.go
  test/e2e/e2e_topologyspreadconstraint_test.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#1110 update v0.26.1 references
  README.md
  docs/user-guide.md
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1111 Delete "io/ioutil" package.
  pkg/descheduler/policyconfig.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1112 Fix typo log message for cachedClient
  pkg/descheduler/descheduler.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1115 bump to k8s 1.27
  .github/workflows/helm.yaml
  Dockerfile
  go.mod
  go.sum
  test/run-e2e-tests.sh
  vendor/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/kmsv2/envelope.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/M, lgtm, approved, tide/merge-method-squash

#1109 update v0.26.1 references
  README.md
  docs/deprecated/v1alpha1.md
  docs/user-guide.md
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1122 Add json tags to internal api fields
  .github/workflows/manifests.yaml
  kubernetes/base/configmap.yaml
  pkg/api/types.go
  test/kind-config.yaml
  test/manifests/v1alpha1/configmap.yaml
  test/manifests/v1alpha2/configmap.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved

#1130 Add knelasevero to approvers
  OWNERS
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1127 Drop remaining mentions of evict extension point
  README.md
  docs/user-guide.md
  examples/failed-pods.yaml
  examples/high-node-utilization.yml
  examples/low-node-utilization.yml
  examples/node-affinity.yml
  examples/pod-life-time.yml
  examples/policy.yaml
  examples/topology-spread-constraint.yaml
  pkg/descheduler/policyconfig_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1132 Add note on documentation versions with links
  README.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#1133 Add missing quote to configmap
  kubernetes/base/configmap.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved
