Repository kubernetes-sigs/descheduler, pull requests merged in 2023-03, with the labels that each got.

#1068 Adding descheduler policy API Version option in helm templates
  charts/descheduler/templates/configmap.yaml
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, tide/merge-method-squash, ok-to-test

#1072 Fix typo in nodeutilization types
  pkg/framework/plugins/nodeutilization/types.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1075 Add note to HighNodeUtilization readme for GKE users
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1066 expose security context from helm chart
  charts/descheduler/templates/cronjob.yaml
  charts/descheduler/templates/deployment.yaml
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#937 remove e2e tests from helm github action
  .github/workflows/helm.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1063 Add k8s compatibility warnings to logs
  pkg/api/v1alpha1/conversion.go
  pkg/descheduler/descheduler.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#1090 docs: typo
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1093 Descheduling profile with PoC fake plugin
  pkg/api/sort.go
  pkg/api/types.go
  pkg/api/v1alpha1/conversion.go
  pkg/api/v1alpha2/sort.go
  pkg/api/v1alpha2/types.go
  pkg/api/v1alpha2/zz_generated.conversion.go
  pkg/api/v1alpha2/zz_generated.deepcopy.go
  pkg/api/zz_generated.deepcopy.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/descheduler_test.go
  pkg/descheduler/policyconfig.go
  pkg/descheduler/policyconfig_test.go
  pkg/framework/fake/plugin/fake.go
  pkg/framework/fake/plugin/fixture.go
  pkg/framework/fake/plugin/zz_generated.deepcopy.go
  pkg/framework/profile/profile.go
  pkg/framework/profile/profile_test.go
  pkg/framework/types.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved, tide/merge-method-squash
