Repository kubernetes-sigs/descheduler, pull requests merged in 2023-06, with the labels that each got.

#1033 pod anti-affinity check among nodes
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, tide/merge-method-squash, ok-to-test

#1166 update pause image from 'kubernetes/pause' to 'registry.k8s.io/pause'
  test/e2e/e2e_duplicatepods_test.go
  test/e2e/e2e_leaderelection_test.go
  test/e2e/e2e_test.go
  test/e2e/e2e_toomanyrestarts_test.go
  test/run-e2e-tests.sh
Labels: cncf-cla: yes, size/S, lgtm, approved

#1173 Replace deprecated command with environment file
  .github/workflows/helm.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1163 use pod informers for listing pods in removepodsviolatingtopologyspreadconstraint and removepodsviolatinginterpodantiaffinity
  pkg/descheduler/pod/pods.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, tide/merge-method-squash

#1174 FakeClientset: bump watch channel size
  cmd/descheduler/app/server.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1177 deschedule/balance order (continuation)
  pkg/descheduler/descheduler.go
Labels: cncf-cla: yes, size/L, lgtm, approved, tide/merge-method-squash
