Repository kubernetes-sigs/descheduler, pull requests merged in 2023-07, with the labels that each got.

#1141 bump log level for processing info
  pkg/framework/plugins/podlifetime/pod_lifetime.go
  pkg/framework/plugins/removeduplicates/removeduplicates.go
  pkg/framework/plugins/removefailedpods/failedpods.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#1203 nodefit: aggregate errors
  pkg/descheduler/node/node.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1207 fix: base configmap missing plugin RemoveDuplicates
  kubernetes/base/configmap.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved
