Repository kubernetes-sigs/descheduler, pull requests merged in 2023-09, with the labels that each got.

#1242 fix: golangci config
  .golangci.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1241 docs: fix evictableNamespaces example
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1246 update image references to point to v0.28.0
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1220 nodefit: use info log level when pod doesn't fit
  pkg/framework/plugins/defaultevictor/defaultevictor.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, tide/merge-method-squash, ok-to-test

#1245 helm: support of `timeZone` for CronJob
  charts/descheduler/README.md
  charts/descheduler/templates/cronjob.yaml
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved
