Repository kubernetes-sigs/descheduler, pull requests merged in 2024-04, with the labels that each got.

#1365 `RemoveDuplicates`: reduce cycle times identifying duplicates
  pkg/framework/plugins/removeduplicates/removeduplicates.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1369 avoid redundant type conversion of DefaultEvictorArgs parameter in DefaultEvictor
  pkg/framework/plugins/defaultevictor/defaultevictor.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1373 bump(golang.org/x/net)=v0.23.0
  go.mod
  go.sum
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64le.s
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/websocket/client.go
  vendor/golang.org/x/net/websocket/dial.go
  vendor/golang.org/x/sys/unix/aliases.go
  vendor/golang.org/x/sys/unix/syscall_darwin_libSystem.go
  vendor/golang.org/x/sys/unix/syscall_freebsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#1342 Allow eviction of DaemonSet pods
  README.md
  charts/descheduler/values.yaml
  docs/deprecated/v1alpha1.md
  pkg/api/v1alpha1/conversion.go
  pkg/api/v1alpha1/types.go
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/componentconfig/types.go
  pkg/apis/componentconfig/v1alpha1/types.go
  pkg/apis/componentconfig/v1alpha1/zz_generated.conversion.go
  pkg/descheduler/policyconfig_test.go
  pkg/framework/plugins/defaultevictor/defaultevictor.go
  pkg/framework/plugins/defaultevictor/defaults.go
  pkg/framework/plugins/defaultevictor/defaults_test.go
  pkg/framework/plugins/defaultevictor/types.go
  test/e2e/e2e_test.go
Labels: kind/feature, cncf-cla: yes, size/L, lgtm, approved, tide/merge-method-squash, ok-to-test

#1374 bump to go 1.22.2
  .github/workflows/helm.yaml
  Dockerfile
  Makefile
  docs/cli/descheduler.md
  go.mod
  hack/update-gofmt.sh
  hack/verify-gofmt.sh
Labels: cncf-cla: yes, size/S, lgtm, approved, tide/merge-method-squash

#1376 helm: Allow the use of existing policy configMap
  charts/descheduler/templates/configmap.yaml
  charts/descheduler/values.yaml
Labels: kind/feature, cncf-cla: yes, size/XS, lgtm, approved, tide/merge-method-squash, ok-to-test

#1379 Fix and improve the namespace filtering description in README
  README.md
Labels: cncf-cla: yes, size/S, lgtm, approved
