Repository kubernetes-sigs/descheduler, pull requests merged in 2024-09, with the labels that each got.

#1507 feat(helm): make securityContext conditional in Deployment and CronJob
  charts/descheduler/templates/cronjob.yaml
  charts/descheduler/templates/deployment.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1480 Plugin args: tag arguments with omitempty to reduce the marshalled json size
  pkg/api/types.go
  pkg/framework/plugins/defaultevictor/types.go
  pkg/framework/plugins/nodeutilization/types.go
  pkg/framework/plugins/podlifetime/types.go
  pkg/framework/plugins/removeduplicates/types.go
  pkg/framework/plugins/removefailedpods/types.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/types.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/types.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/types.go
  pkg/framework/plugins/removepodsviolatingnodetaints/types.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/types.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1506 descheduler v0.31: update docs and manifests
  README.md
  docs/user-guide.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#1508 [e2e] no test timeouts, produce the same image tag as in production
  test/run-e2e-tests.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1510 chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`
  go.mod
  go.sum
  test/e2e/e2e_test.go
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/XL, lgtm, kind/cleanup, approved, ok-to-test

#1511 descheduler v0.31.0: bump kustomize files
  .github/workflows/manifests.yaml
  README.md
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1513 chore: bump golangci-lint to latest
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1512 descheduler v0.31.0: bump helm chart
  charts/descheduler/Chart.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1514 fix: github action Release Charts to have write permissions
  .github/workflows/release.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1517 [e2e] abstract common methods
  test/e2e/e2e_failedpods_test.go
  test/e2e/e2e_leaderelection_test.go
  test/e2e/e2e_test.go
  test/e2e/e2e_toomanyrestarts_test.go
  test/e2e/e2e_topologyspreadconstraint_test.go
  test/e2e/test_clientconnection_test.go
  test/test_utils.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1520 [DuplicatePods] e2e: build a descheduler image and run the descheduler as a pod
  test/e2e/e2e_duplicatepods_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1521 [FailedPods] e2e: build a descheduler image and run the descheduler as a pod
  test/e2e/e2e_failedpods_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1523 [TopologySpreadConstraint] e2e: build a descheduler image and run the descheduler as a pod
  test/e2e/e2e_topologyspreadconstraint_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test
