Repository kubernetes-sigs/descheduler, pull requests merged in 2024-12, with the labels that each got.

#1565 Bump to Go 1.23.3
  Dockerfile
  docs/contributor-guide.md
  go.mod
  hack/lib/go.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1567 Bump golangci-lint to 1.62.2
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1568 Bump kind version to v0.25.0
  test/run-e2e-tests.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1571 Bump golangci-lint timeout from 2m to 5m
  .golangci.yml
Labels: cncf-cla: yes, size/XS, lgtm, kind/cleanup, approved

#1572 Enable golangci-lint Verbose Output
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, kind/cleanup, approved

#1570 docs: Removing deschedulerPolicy.strategies since it does not exist
  charts/descheduler/README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1573 Fixed the issue when successfulJobsHistoryLimit and failedJobsHistoryLimit variables are 0.
  charts/descheduler/templates/cronjob.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1576 Bump kind to v0.26.0
  test/run-e2e-tests.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1564 Improve chart default values
  charts/descheduler/templates/cronjob.yaml
  charts/descheduler/templates/deployment.yaml
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1575 bump to official kubernetes v0.32.0 deps
  go.mod
  go.sum
  vendor/k8s.io/utils/clock/testing/fake_clock.go
  vendor/k8s.io/utils/lru/lru.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/L, lgtm, approved

#1536 feature(eviction): add event when EvictPod failed
  pkg/api/types.go
  pkg/api/v1alpha2/types.go
  pkg/api/v1alpha2/zz_generated.conversion.go
  pkg/api/v1alpha2/zz_generated.deepcopy.go
  pkg/api/zz_generated.deepcopy.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/evictions/evictions_test.go
  pkg/descheduler/evictions/options.go
Labels: kind/feature, cncf-cla: yes, size/L, lgtm, approved

#1587 [release v0.32] update kubernetes kind version to 1.32
  .github/workflows/manifests.yaml
  test/run-e2e-tests.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1588 [release v0.32] update docs/readme
  README.md
  docs/user-guide.md
Labels: cncf-cla: yes, size/S, lgtm, approved
