Repository kubernetes-sigs/descheduler, pull requests merged in 2024-06, with the labels that each got.

#1395 fix the issue that the pod anti-filtering rules are not taking effect
  pkg/descheduler/node/node.go
  pkg/descheduler/node/node_test.go
  pkg/utils/predicates.go
  pkg/utils/priority.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1425 Automated cherry pick of #1378: Fix the replicas type for the helm-chart #1390: allow 'falsey' value in cmdOption #1412: fix helm's default deschedulerPolicy #1413: fix TOC location in Readme #1416: use cmd context instead of using context.Background() #1395: fix the issue that the pod anti-filtering rules are not
  README.md
  charts/descheduler/templates/NOTES.txt
  charts/descheduler/templates/cronjob.yaml
  charts/descheduler/templates/deployment.yaml
  charts/descheduler/values.yaml
  cmd/descheduler/app/server.go
  pkg/descheduler/node/node.go
  pkg/descheduler/node/node_test.go
  pkg/utils/predicates.go
  pkg/utils/priority.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1427 helm: upgrade to v0.30.1
  charts/descheduler/Chart.yaml
  docs/deprecated/v1alpha1.md
  docs/user-guide.md
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1429 Bump otel semconv to 1.24
  cmd/descheduler/app/server.go
  pkg/tracing/tracing.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1432 chore: reduce repetition of go versions
  .github/workflows/helm.yaml
  Makefile
  hack/lib/go.sh
  hack/update-gofmt.sh
  hack/verify-gofmt.sh
Labels: cncf-cla: yes, size/M, lgtm, approved

#1433 bump go to 1.22.4 for CVE-2024-24790 and CVE-2024-24789
  Dockerfile
  go.mod
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1435 return pod qos in advance
  pkg/utils/qos.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1441 refactor some methods in e2e test
  test/e2e/e2e_duplicatepods_test.go
  test/e2e/e2e_failedpods_test.go
  test/e2e/e2e_leaderelection_test.go
  test/e2e/e2e_test.go
  test/e2e/e2e_toomanyrestarts_test.go
  test/e2e/e2e_topologyspreadconstraint_test.go
Labels: cncf-cla: yes, size/M, lgtm, kind/cleanup, approved

#1431 Automated cherry pick of #1427: helm: upgrade to v0.30.1
  charts/descheduler/Chart.yaml
  docs/deprecated/v1alpha1.md
  docs/user-guide.md
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1438 chore: cleanup duplicated code
  pkg/descheduler/descheduler.go
Labels: cncf-cla: yes, size/XS, lgtm, kind/cleanup, approved

#1442 Update README.md
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1446 fix: return the unmatched cases first
  pkg/descheduler/pod/pods.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1445 Unit-test: add necessary ownerRef to the pod.
  pkg/framework/plugins/nodeutilization/highnodeutilization_test.go
  pkg/framework/plugins/nodeutilization/lownodeutilization_test.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts_test.go
  pkg/framework/plugins/removepodsviolatingnodetaints/node_taint_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#1447 PodEvictor: refactoring and preparation for eviction requests
  pkg/descheduler/descheduler.go
  pkg/descheduler/descheduler_test.go
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/evictions/evictions_test.go
  pkg/framework/plugins/nodeutilization/highnodeutilization_test.go
  pkg/framework/plugins/nodeutilization/lownodeutilization_test.go
  pkg/framework/plugins/podlifetime/pod_lifetime_test.go
  pkg/framework/plugins/removeduplicates/removeduplicates_test.go
  pkg/framework/plugins/removefailedpods/failedpods_test.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts_test.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity_test.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity_test.go
  pkg/framework/plugins/removepodsviolatingnodetaints/node_taint_test.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint_test.go
  pkg/framework/profile/profile_test.go
  test/e2e/e2e_duplicatepods_test.go
  test/e2e/e2e_failedpods_test.go
  test/e2e/e2e_test.go
  test/e2e/e2e_toomanyrestarts_test.go
  test/e2e/e2e_topologyspreadconstraint_test.go
Labels: cncf-cla: yes, size/L, lgtm, kind/cleanup, approved

#1448 Update options.go
  cmd/descheduler/app/options/options.go
Labels: cncf-cla: yes, size/XS, lgtm, kind/cleanup, do-not-merge/hold, approved, ok-to-test

#1436 return node fit error in advance
  pkg/descheduler/node/node.go
  pkg/descheduler/node/node_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test
