Repository kubernetes-sigs/descheduler, pull requests merged in 2024-03, with the labels that each got.

#1349 Improve PodEvictor observability through EvictOptions
  metrics/metrics.go
  pkg/descheduler/evictions/evictions.go
  pkg/framework/plugins/nodeutilization/highnodeutilization.go
  pkg/framework/plugins/nodeutilization/lownodeutilization.go
  pkg/framework/plugins/nodeutilization/nodeutilization.go
  pkg/framework/plugins/podlifetime/pod_lifetime.go
  pkg/framework/plugins/removeduplicates/removeduplicates.go
  pkg/framework/plugins/removefailedpods/failedpods.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity.go
  pkg/framework/plugins/removepodsviolatingnodetaints/node_taint.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint.go
  pkg/framework/profile/profile.go
  pkg/framework/profile/profile_test.go
Labels: kind/feature, cncf-cla: yes, size/M, lgtm, approved, tide/merge-method-squash, ok-to-test

#1358 Fix node taint wrong EvictOption field
  pkg/framework/plugins/removepodsviolatingnodetaints/node_taint.go
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1362 Disambiguate node fit log messages
  pkg/descheduler/node/node.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1356 Check whether pod matches the inter-pod anti-affinity of another Pod in a given Node in `NodeFit()`
  README.md
  pkg/descheduler/node/node.go
  pkg/descheduler/node/node_test.go
  pkg/descheduler/pod/pods.go
  pkg/descheduler/pod/pods_test.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity_test.go
  pkg/utils/predicates.go
  pkg/utils/predicates_test.go
  pkg/utils/priority.go
  test/run-e2e-tests.sh
  test/test_utils.go
Labels: cncf-cla: yes, size/L, lgtm, approved, tide/merge-method-squash, ok-to-test

#1257 skip eviction when replica count is below evictor `minReplicas` threshold setting
  README.md
  pkg/descheduler/pod/pods.go
  pkg/framework/plugins/defaultevictor/defaultevictor.go
  pkg/framework/plugins/defaultevictor/defaultevictor_test.go
  pkg/framework/plugins/defaultevictor/types.go
  pkg/framework/plugins/defaultevictor/validation.go
  test/e2e/e2e_duplicatepods_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, needs-rebase

#1360 Add argument to remove only pods violating allowlisted taints
  README.md
  pkg/api/v1alpha1/types.go
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/framework/plugins/removepodsviolatingnodetaints/defaults.go
  pkg/framework/plugins/removepodsviolatingnodetaints/defaults_test.go
  pkg/framework/plugins/removepodsviolatingnodetaints/node_taint.go
  pkg/framework/plugins/removepodsviolatingnodetaints/node_taint_test.go
  pkg/framework/plugins/removepodsviolatingnodetaints/types.go
  pkg/framework/plugins/removepodsviolatingnodetaints/validation.go
  pkg/framework/plugins/removepodsviolatingnodetaints/validation_test.go
  pkg/framework/plugins/removepodsviolatingnodetaints/zz_generated.deepcopy.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1139 use v1alpha2 api for helm chart default values
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, tide/merge-method-squash
