Repository kubernetes-sigs/descheduler, pull requests merged in 2024-07, with the labels that each got.

#1454 test: generate uid when building a pod
  test/test_utils.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1455 feat: pod evictor options
  pkg/descheduler/descheduler.go
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/evictions/evictions_test.go
  pkg/descheduler/evictions/options.go
  pkg/framework/plugins/nodeutilization/highnodeutilization_test.go
  pkg/framework/plugins/nodeutilization/lownodeutilization_test.go
  pkg/framework/plugins/podlifetime/pod_lifetime_test.go
  pkg/framework/plugins/removeduplicates/removeduplicates_test.go
  pkg/framework/plugins/removefailedpods/failedpods_test.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts_test.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity_test.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity_test.go
  pkg/framework/plugins/removepodsviolatingnodetaints/node_taint_test.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint_test.go
  pkg/framework/profile/profile_test.go
  test/e2e/e2e_duplicatepods_test.go
  test/e2e/e2e_test.go
  test/e2e/e2e_toomanyrestarts_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1452 fix: indexer cache error when default evictor is re-initialized
  pkg/framework/plugins/defaultevictor/defaultevictor.go
  pkg/framework/plugins/defaultevictor/defaultevictor_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1457 fix: add info for error return
  pkg/descheduler/client/client.go
Labels: cncf-cla: yes, size/XS, lgtm, kind/cleanup, approved

#1456 PodEvictor: turn an exceeded limit into an error
  pkg/api/v1alpha1/conversion.go
  pkg/descheduler/evictions/errors.go
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/evictions/evictions_test.go
  pkg/framework/fake/fake.go
  pkg/framework/plugins/nodeutilization/nodeutilization.go
  pkg/framework/plugins/podlifetime/pod_lifetime.go
  pkg/framework/plugins/removeduplicates/removeduplicates.go
  pkg/framework/plugins/removefailedpods/failedpods.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity.go
  pkg/framework/plugins/removepodsviolatingnodetaints/node_taint.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint.go
  pkg/framework/profile/profile.go
  pkg/framework/profile/profile_test.go
  pkg/framework/types/types.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1459 descheduler_test.go refactoring
  pkg/descheduler/descheduler_test.go
  pkg/descheduler/policyconfig_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1451 The descheduler supports limiting the total number of pods evicted per rescheduling cycle
  pkg/api/types.go
  pkg/api/v1alpha1/types.go
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/api/v1alpha2/types.go
  pkg/api/v1alpha2/zz_generated.conversion.go
  pkg/api/v1alpha2/zz_generated.deepcopy.go
  pkg/api/zz_generated.deepcopy.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/evictions/errors.go
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/evictions/options.go
  pkg/framework/plugins/nodeutilization/lownodeutilization_test.go
  pkg/framework/plugins/nodeutilization/nodeutilization.go
  pkg/framework/plugins/podlifetime/pod_lifetime.go
  pkg/framework/plugins/podlifetime/pod_lifetime_test.go
  pkg/framework/plugins/removeduplicates/removeduplicates.go
  pkg/framework/plugins/removefailedpods/failedpods.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity_test.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity_test.go
  pkg/framework/plugins/removepodsviolatingnodetaints/node_taint.go
  pkg/framework/plugins/removepodsviolatingnodetaints/node_taint_test.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint.go
Labels: kind/feature, cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1460 descheduler_test.go: initDescheduler: pass a new ctx with cancel inst…
  pkg/descheduler/descheduler_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#1458 pod evictor: make it thread safe
  pkg/descheduler/evictions/evictions.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#1463 Update README about maxNoOfPodsToEvictTotal
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1464 refactor: replace k8s.io/utils/pointer with k8s.io/utils/ptr
  go.mod
  go.sum
  pkg/api/v1alpha1/strategymigration.go
  pkg/api/v1alpha1/strategymigration_test.go
  pkg/descheduler/evictions/evictions_test.go
  pkg/descheduler/policyconfig_test.go
  pkg/framework/plugins/defaultevictor/defaults_test.go
  pkg/framework/plugins/podlifetime/defaults_test.go
  pkg/framework/plugins/removefailedpods/defaults.go
  pkg/framework/plugins/removefailedpods/defaults_test.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/defaults.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/defaults_test.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint_test.go
  test/e2e/e2e_duplicatepods_test.go
  test/e2e/e2e_failedpods_test.go
  test/e2e/e2e_leaderelection_test.go
  test/e2e/e2e_test.go
  test/e2e/e2e_toomanyrestarts_test.go
  test/test_utils.go
  vendor/k8s.io/utils/net/multi_listen.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1444 feat: Add namespace override settings in Helm Chart
  charts/descheduler/README.md
  charts/descheduler/templates/_helpers.tpl
  charts/descheduler/templates/clusterrolebinding.yaml
  charts/descheduler/templates/configmap.yaml
  charts/descheduler/templates/cronjob.yaml
  charts/descheduler/templates/deployment.yaml
  charts/descheduler/templates/service.yaml
  charts/descheduler/templates/serviceaccount.yaml
  charts/descheduler/templates/servicemonitor.yaml
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1443 fix: helm leader-election typo to `resourceNamespace`
  charts/descheduler/templates/_helpers.tpl
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1467 helm unit tests
  .github/workflows/helm.yaml
  charts/descheduler/tests/.gitignore
  charts/descheduler/tests/cronjob_test.yaml
  charts/descheduler/tests/deployment_test.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved

#1473 bump(github.com/golangci/golangci-lint)=v1.59.1
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1472 e2e: TestTooManyRestarts: run descheduler as a whole instead of a single plugin
  test/e2e/e2e_test.go
  test/e2e/e2e_toomanyrestarts_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1471 e2e: TestRemoveDuplicates: limit the tested namespace
  test/e2e/e2e_duplicatepods_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1354 KEP-1397: descheduler integration with evacuation API as an alternative to eviction API
  keps/1397-evictions-in-background/README.md
  keps/1397-evictions-in-background/kep.yaml
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#1475 skip eviction when pod creation time is below minPodAge threshold setting
  README.md
  pkg/framework/plugins/defaultevictor/defaultevictor.go
  pkg/framework/plugins/defaultevictor/defaultevictor_test.go
  pkg/framework/plugins/defaultevictor/types.go
  pkg/framework/plugins/defaultevictor/zz_generated.deepcopy.go
Labels: cncf-cla: yes, size/M, lgtm, approved, tide/merge-method-squash, ok-to-test

#1430 fix: minor version parsing in version compatibility check
  pkg/descheduler/descheduler.go
  pkg/descheduler/descheduler_test.go
  pkg/version/version_test.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/XL, lgtm, approved

#1469 e2e: TestLeaderElection: delete the lease and increase the retry period
  test/e2e/e2e_leaderelection_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved
