Repository kubernetes-sigs/descheduler, pull requests merged in 2024-05, with the labels that each got.

#1381 Add an extra parameter ExitCode to RemoveFailedPods
  README.md
  pkg/framework/plugins/removefailedpods/failedpods.go
  pkg/framework/plugins/removefailedpods/failedpods_test.go
  pkg/framework/plugins/removefailedpods/types.go
  pkg/framework/plugins/removefailedpods/zz_generated.deepcopy.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1372 753 - Descheduling framework
  keps/753-descheduling-framework/README.md
  keps/753-descheduling-framework/framework-workflow-diagram.png
  keps/753-descheduling-framework/kep.yaml
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#1396 KEP-753: Descheduling framework: update diagram
  keps/753-descheduling-framework/framework-workflow-diagram.png
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1408 bump to to 1.22.3 to address CVE-2024-24788
  .github/workflows/helm.yaml
  Dockerfile
  Makefile
  go.mod
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1405 [release 1.30] update kustomize image tags and helm versions
  .github/workflows/manifests.yaml
  charts/descheduler/Chart.yaml
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1378 Fix the replicas value type for the descheduler helm-chart
  charts/descheduler/templates/NOTES.txt
  charts/descheduler/templates/deployment.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1390 Helm chart - allow 'falsey' value in cmdOption
  charts/descheduler/templates/cronjob.yaml
  charts/descheduler/templates/deployment.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1412 fix helm's default deschedulerPolicy
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1413 fix TOC location in Readme
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1416 use cmd context instead of using context.Background()
  cmd/descheduler/app/server.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test
