Repository kubernetes-sigs/descheduler, pull requests merged in 2024-01, with the labels that each got.

#1335 v0.29.0: bump helm chart and update manifests/docs
  .github/workflows/manifests.yaml
  Makefile
  README.md
  charts/descheduler/Chart.yaml
  docs/deprecated/v1alpha1.md
  docs/user-guide.md
  hack/kind_config.yaml
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1334 fix(podlifetime): fix failed unittest
  pkg/framework/plugins/podlifetime/pod_lifetime.go
  pkg/framework/plugins/podlifetime/pod_lifetime_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1337 v1alpha1: log deprecation notice
  pkg/api/v1alpha1/conversion.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1289 feat: Add support for topologySpreadConstraints
  charts/descheduler/README.md
  charts/descheduler/templates/cronjob.yaml
  charts/descheduler/templates/deployment.yaml
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test
