Repository kubernetes-sigs/descheduler, pull requests merged in 2024-08, with the labels that each got.

#1476 bump go to 1.22.5
  Dockerfile
  go.mod
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1474 [TestTooManyRestarts] e2e: build a descheduler image and run the descheduler as a pod
  go.mod
  go.sum
  test/e2e/e2e_test.go
  test/e2e/e2e_toomanyrestarts_test.go
  test/run-e2e-tests.sh
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#1479 docs: Provide OCI annotation for where to find image sources
  Dockerfile
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1482 Remove descheduler/v1alpha1 type
  .github/workflows/manifests.yaml
  docs/deprecated/v1alpha1.md
  hack/update-generated-defaulters.sh
  pkg/api/v1alpha1/conversion.go
  pkg/api/v1alpha1/defaults.go
  pkg/api/v1alpha1/doc.go
  pkg/api/v1alpha1/register.go
  pkg/api/v1alpha1/strategymigration.go
  pkg/api/v1alpha1/strategymigration_test.go
  pkg/api/v1alpha1/types.go
  pkg/api/v1alpha1/zz_generated.deepcopy.go
  pkg/api/v1alpha1/zz_generated.defaults.go
  pkg/descheduler/policyconfig.go
  pkg/descheduler/policyconfig_test.go
  pkg/descheduler/scheme/scheme.go
  test/e2e/policy_leaderelection_a.yaml
  test/e2e/policy_leaderelection_b.yaml
  test/manifests/v1alpha1/configmap.yaml
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#1483 tests: de-duplicate framework handle initialization
  pkg/framework/plugins/nodeutilization/highnodeutilization_test.go
  pkg/framework/plugins/nodeutilization/lownodeutilization_test.go
  pkg/framework/plugins/podlifetime/pod_lifetime_test.go
  pkg/framework/plugins/removeduplicates/removeduplicates_test.go
  pkg/framework/plugins/removefailedpods/failedpods_test.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts_test.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity_test.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity_test.go
  pkg/framework/plugins/removepodsviolatingnodetaints/node_taint_test.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint_test.go
  pkg/framework/profile/profile_test.go
  pkg/framework/testing/utils.go
  test/e2e/e2e_duplicatepods_test.go
  test/e2e/e2e_failedpods_test.go
  test/e2e/e2e_test.go
  test/e2e/e2e_topologyspreadconstraint_test.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#1484 [unit test]: test descheduling limits
  pkg/descheduler/descheduler_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#1485 [unit test]: simplify test pod evictor reset
  pkg/descheduler/descheduler_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#1498 README: drop v1alpha1 descheduler policy mention
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1505 chore: upgrade python EOL and action versions
  .github/workflows/helm.yaml
  .github/workflows/manifests.yaml
  .github/workflows/release.yaml
  .github/workflows/security.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1504 descheduler v0.31: update e2e test versions
  .github/workflows/manifests.yaml
  Makefile
  test/run-e2e-tests.sh
Labels: cncf-cla: yes, size/S, lgtm, approved
