Repository kubernetes-sigs/descheduler, pull requests merged in 2025-04, with the labels that each got.

#1661 TestLowNodeUtilizationKubernetesMetrics: set the right -cpu value for the cpu stressor
  test/e2e/e2e_lownodeutilization_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1662 TestLowNodeUtilizationKubernetesMetrics: set the right -cpu value for the cpu stressor
  test/e2e/e2e_lownodeutilization_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1663 feat: introduce strict eviction policy
  README.md
  pkg/framework/plugins/nodeutilization/highnodeutilization.go
  pkg/framework/plugins/nodeutilization/highnodeutilization_test.go
  pkg/framework/plugins/nodeutilization/nodeutilization.go
  pkg/framework/plugins/nodeutilization/types.go
  pkg/framework/plugins/nodeutilization/validation.go
  pkg/framework/plugins/nodeutilization/zz_generated.deepcopy.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1667 chore: update owners to add me as reviewer
  OWNERS
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1676 fix: update the mailing list address
  Dockerfile
  Dockerfile.dev
  charts/descheduler/Chart.yaml
  docs/release-guide.md
Labels: cncf-cla: yes, size/S, lgtm, approved
