Repository kubernetes-sigs/descheduler, pull requests merged in 2025-03, with the labels that each got.

#1637 chore: add setDefaultEvictor return an error
  pkg/descheduler/policyconfig.go
  pkg/descheduler/policyconfig_test.go
  pkg/utils/predicates.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#1640 ReferencedResourceList: alias for map[v1.ResourceName]*resource.Quantity to avoid the type definition duplication
  pkg/api/types.go
  pkg/descheduler/metricscollector/metricscollector.go
  pkg/descheduler/metricscollector/metricscollector_test.go
  pkg/descheduler/node/node.go
  pkg/framework/plugins/nodeutilization/highnodeutilization.go
  pkg/framework/plugins/nodeutilization/lownodeutilization.go
  pkg/framework/plugins/nodeutilization/nodeutilization.go
  pkg/framework/plugins/nodeutilization/nodeutilization_test.go
  pkg/framework/plugins/nodeutilization/usageclients.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1642 lownodeutilization: evictionLimits to limit the evictions per plugin
  README.md
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/framework/plugins/nodeutilization/highnodeutilization.go
  pkg/framework/plugins/nodeutilization/lownodeutilization.go
  pkg/framework/plugins/nodeutilization/lownodeutilization_test.go
  pkg/framework/plugins/nodeutilization/nodeutilization.go
  pkg/framework/plugins/nodeutilization/types.go
  pkg/framework/plugins/nodeutilization/zz_generated.deepcopy.go
Labels: kind/feature, cncf-cla: yes, size/L, lgtm, approved

#1644 nodeutilization: invoke ValidateLowNodeUtilizationArgs instead of validateLowNodeUtilizationThresholds to make the test more generic
  pkg/framework/plugins/nodeutilization/validation_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1645 nodeutilization: make the node classification more generic
  pkg/framework/plugins/nodeutilization/highnodeutilization.go
  pkg/framework/plugins/nodeutilization/lownodeutilization.go
  pkg/framework/plugins/nodeutilization/nodeutilization.go
  pkg/framework/plugins/nodeutilization/nodeutilization_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1614 [nodeutilization]: allow to set a metrics source as a string so it can be later extended for exclusive configuration
  README.md
  charts/descheduler/templates/clusterrole.yaml
  charts/descheduler/values.yaml
  pkg/api/types.go
  pkg/api/v1alpha2/types.go
  pkg/api/v1alpha2/zz_generated.conversion.go
  pkg/api/v1alpha2/zz_generated.deepcopy.go
  pkg/api/zz_generated.deepcopy.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/descheduler_test.go
  pkg/descheduler/policyconfig.go
  pkg/descheduler/policyconfig_test.go
  pkg/framework/plugins/nodeutilization/lownodeutilization.go
  pkg/framework/plugins/nodeutilization/lownodeutilization_test.go
  pkg/framework/plugins/nodeutilization/types.go
  pkg/framework/plugins/nodeutilization/zz_generated.deepcopy.go
  test/e2e/e2e_lownodeutilization_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1533 [lownodeutilization]: Actual utilization: integration with Prometheus
  README.md
  cmd/descheduler/app/options/options.go
  go.mod
  go.sum
  kubernetes/base/rbac.yaml
  pkg/api/types.go
  pkg/api/v1alpha2/types.go
  pkg/api/v1alpha2/zz_generated.conversion.go
  pkg/api/v1alpha2/zz_generated.deepcopy.go
  pkg/api/zz_generated.deepcopy.go
  pkg/descheduler/client/client.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/descheduler_test.go
  pkg/descheduler/policyconfig.go
  pkg/descheduler/policyconfig_test.go
  pkg/framework/fake/fake.go
  pkg/framework/plugins/nodeutilization/highnodeutilization.go
  pkg/framework/plugins/nodeutilization/lownodeutilization.go
  pkg/framework/plugins/nodeutilization/lownodeutilization_test.go
  pkg/framework/plugins/nodeutilization/nodeutilization.go
  pkg/framework/plugins/nodeutilization/types.go
  pkg/framework/plugins/nodeutilization/usageclients.go
  pkg/framework/plugins/nodeutilization/usageclients_test.go
  pkg/framework/plugins/nodeutilization/validation.go
  pkg/framework/plugins/nodeutilization/validation_test.go
  pkg/framework/plugins/nodeutilization/zz_generated.deepcopy.go
  pkg/framework/profile/profile.go
  pkg/framework/types/types.go
  vendor/github.com/jpillora/backoff/LICENSE
  vendor/github.com/jpillora/backoff/README.md
  vendor/github.com/jpillora/backoff/backoff.go
  vendor/github.com/mwitkow/go-conntrack/.gitignore
  vendor/github.com/mwitkow/go-conntrack/.travis.yml
  vendor/github.com/mwitkow/go-conntrack/LICENSE
  vendor/github.com/mwitkow/go-conntrack/README.md
  vendor/github.com/mwitkow/go-conntrack/dialer_reporter.go
  vendor/github.com/mwitkow/go-conntrack/dialer_wrapper.go
  vendor/github.com/mwitkow/go-conntrack/listener_reporter.go
  vendor/github.com/mwitkow/go-conntrack/listener_wrapper.go
  vendor/github.com/prometheus/client_golang/api/client.go
  vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
  vendor/github.com/prometheus/common/config/config.go
  vendor/github.com/prometheus/common/config/headers.go
  vendor/github.com/prometheus/common/config/http_config.go
  vendor/golang.org/x/net/http/httpproxy/proxy.go
  vendor/golang.org/x/oauth2/clientcredentials/clientcredentials.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#1652 [nodeutilization]: produce node utilization of resources that are listed in the list of resources
  pkg/descheduler/node/node.go
  pkg/framework/plugins/nodeutilization/usageclients.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#1649 feat: refactoring thresholds and usage assessment
  go.mod
  pkg/framework/plugins/nodeutilization/highnodeutilization.go
  pkg/framework/plugins/nodeutilization/highnodeutilization_test.go
  pkg/framework/plugins/nodeutilization/lownodeutilization.go
  pkg/framework/plugins/nodeutilization/lownodeutilization_test.go
  pkg/framework/plugins/nodeutilization/nodeutilization.go
  pkg/framework/plugins/nodeutilization/nodeutilization_test.go
  pkg/framework/plugins/nodeutilization/normalizer/normalizer.go
  pkg/framework/plugins/nodeutilization/normalizer/normalizer_test.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved, ok-to-test

#1653 feat: move classifier to its own package
  pkg/framework/plugins/nodeutilization/classifier/classifier.go
  pkg/framework/plugins/nodeutilization/classifier/classifier_test.go
  pkg/framework/plugins/nodeutilization/highnodeutilization.go
  pkg/framework/plugins/nodeutilization/lownodeutilization.go
  pkg/framework/plugins/nodeutilization/nodeutilization.go
  pkg/framework/plugins/nodeutilization/nodeutilization_test.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved, ok-to-test

#1580 Mention cmdOptions.dry-run in the helm chart readme
  charts/descheduler/README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1654 nominate googs1025 for descheduler reviewers
  OWNERS
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/documentation

#1657 chore: log average and assessed thresholds
  pkg/framework/plugins/nodeutilization/highnodeutilization.go
  pkg/framework/plugins/nodeutilization/lownodeutilization.go
  pkg/framework/plugins/nodeutilization/nodeutilization.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#1629 fix removepodsviolatingtopologyspreadconstraint plugin sort logic
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint_test.go
Labels: kind/bug, cncf-cla: yes, size/L, lgtm, approved
