Repository kubernetes-sigs/descheduler, pull requests merged in 2025-08, with the labels that each got.

#1665 add PodProtections for DefaultEvictorArgs
  README.md
  pkg/descheduler/policyconfig.go
  pkg/descheduler/policyconfig_test.go
  pkg/framework/plugins/defaultevictor/defaultevictor.go
  pkg/framework/plugins/defaultevictor/defaultevictor_test.go
  pkg/framework/plugins/defaultevictor/defaults_test.go
  pkg/framework/plugins/defaultevictor/types.go
  pkg/framework/plugins/defaultevictor/validation.go
  pkg/framework/plugins/defaultevictor/validation_test.go
  pkg/framework/plugins/defaultevictor/zz_generated.deepcopy.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#1729 Improves the validation logic in the plugins
  pkg/framework/plugins/defaultevictor/validation.go
  pkg/framework/plugins/defaultevictor/validation_test.go
  pkg/framework/plugins/podlifetime/validation.go
  pkg/framework/plugins/podlifetime/validation_test.go
  pkg/framework/plugins/removeduplicates/validation.go
  pkg/framework/plugins/removeduplicates/validation_test.go
  pkg/framework/plugins/removefailedpods/validation.go
  pkg/framework/plugins/removefailedpods/validation_test.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/validation.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/validation_test.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/validation.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/validation_test.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/validation.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/validation_test.go
  pkg/framework/plugins/removepodsviolatingnodetaints/validation.go
  pkg/framework/plugins/removepodsviolatingnodetaints/validation_test.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/validation_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1641 feat(token): automountServiceAccountToken set hard to true on deployment
  charts/descheduler/templates/cronjob.yaml
  charts/descheduler/templates/deployment.yaml
  charts/descheduler/templates/serviceaccount.yaml
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#1725 standardize protectionEnabled param across eviction constraints
  pkg/framework/plugins/defaultevictor/constraints.go
  pkg/framework/plugins/defaultevictor/defaultevictor.go
  pkg/framework/plugins/defaultevictor/defaultevictor_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1736 [1732] chore: add cronjob/job labels and annotations to helm chart
  charts/descheduler/README.md
  charts/descheduler/templates/cronjob.yaml
  charts/descheduler/tests/cronjob_annotations_test.yaml
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test
