Repository kubernetes-sigs/descheduler, pull requests merged in 2025-09, with the labels that each got.

#1742 chore: add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#1743 feat(test/e2e): introduce new flags to override RunAsUser and RunAsGroup security context setting
  test/e2e/e2e_test.go
  test/run-e2e-tests.sh
Labels: cncf-cla: yes, size/M, lgtm, approved

#1741 helm chart - Allow to add custom annotations for deployment
  charts/descheduler/templates/deployment.yaml
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1747 chore: give tracing.Shutdown() its own context
  cmd/descheduler/app/server.go
Labels: cncf-cla: yes, size/S, lgtm, approved
