Repository kubernetes-sigs/descheduler, pull requests merged in 2025-01, with the labels that each got.

#1592 [release v0.32.0] bump chart and images
  .github/workflows/manifests.yaml
  README.md
  charts/descheduler/Chart.yaml
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1600 Automated cherry pick of #1591: bump x/net and x/crypto deps for CVE-2024-45337 and
  go.mod
  go.sum
  vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.s
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/sys/cpu/asm_darwin_x86_gc.s
  vendor/golang.org/x/sys/cpu/cpu_darwin_x86.go
  vendor/golang.org/x/sys/cpu/cpu_gc_x86.go
  vendor/golang.org/x/sys/cpu/cpu_gc_x86.s
  vendor/golang.org/x/sys/cpu/cpu_gccgo_x86.go
  vendor/golang.org/x/sys/cpu/cpu_linux_arm64.go
  vendor/golang.org/x/sys/cpu/cpu_other_x86.go
  vendor/golang.org/x/sys/cpu/cpu_x86.go
  vendor/golang.org/x/sys/cpu/syscall_darwin_x86_gc.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/README.md
  vendor/modules.txt
Labels: kind/bug, cncf-cla: yes, size/XXL, lgtm, approved

#1601 [v0.32.1] patch release for CVE-2024-45337 and CVE-2024-45338
  .github/workflows/manifests.yaml
  charts/descheduler/Chart.yaml
  docs/user-guide.md
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1602 chore: add ignorePvcPods param in default evictor filter unit test
  pkg/framework/plugins/defaultevictor/defaultevictor_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#1538 feature(descheduler): add grace_period_seconds for DeschedulerPolicy
  README.md
  pkg/api/types.go
  pkg/api/v1alpha2/types.go
  pkg/api/v1alpha2/zz_generated.conversion.go
  pkg/api/v1alpha2/zz_generated.deepcopy.go
  pkg/api/zz_generated.deepcopy.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/evictions/evictions.go
  pkg/descheduler/evictions/options.go
  test/e2e/e2e_toomanyrestarts_test.go
Labels: kind/feature, cncf-cla: yes, size/M, lgtm, approved

#1596 charts: add missing permission for policy
  charts/descheduler/templates/clusterrole.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1606 flake: rollback gracePeriod for evict pod in e2e test
  test/e2e/e2e_toomanyrestarts_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#1599 charts: add needed perms if metricsCollector is enabled
  charts/descheduler/templates/clusterrole.yaml
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1612 tracing: test for and address semconv/SDK version conflicts
  pkg/tracing/tracing.go
  pkg/tracing/tracing_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test
