Repository kubernetes-sigs/descheduler, pull requests merged in 2025-02, with the labels that each got.

#1621 Automated cherry pick of #1596: charts: add missing permission for policy at ClusterRole
  charts/descheduler/templates/clusterrole.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1628 v0.32.2: bump chart/images
  .github/workflows/manifests.yaml
  charts/descheduler/Chart.yaml
  docs/user-guide.md
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1632 PodMatchNodeSelector: Replaced PodMatchNodeSelector implementation wi…
  pkg/utils/predicates.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#1636 chore: add descheduler plugin example
  pkg/framework/plugins/example/README.md
  pkg/framework/plugins/example/defaults.go
  pkg/framework/plugins/example/docs.go
  pkg/framework/plugins/example/example.go
  pkg/framework/plugins/example/register.go
  pkg/framework/plugins/example/types.go
  pkg/framework/plugins/example/validation.go
  pkg/framework/plugins/example/zz_generated.deepcopy.go
  pkg/framework/plugins/example/zz_generated.defaults.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test
