Repository kubernetes-sigs/descheduler, pull requests merged in 2025-05, with the labels that each got.

#1672 add miss evictDaemonSetPods param in README.md
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1678 [v0.33.0] update docs and manifests
  .github/workflows/manifests.yaml
  README.md
  docs/user-guide.md
  kubernetes/cronjob/cronjob.yaml
  kubernetes/deployment/deployment.yaml
  kubernetes/job/job.yaml
  test/run-e2e-tests.sh
Labels: cncf-cla: yes, size/S, lgtm, approved

#1674 Remove reference to obsolete deschedulerPolicy fields in chart values
  charts/descheduler/values.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1680 v0.33.0: bump helm chart
  README.md
  charts/descheduler/Chart.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1681 optimize: NodeFit function by reordering checks for performance
  pkg/descheduler/node/node.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#1686 feature: sort pods by restarts count in RemovePodsHavingTooManyRestarts plugin
  pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#1684 chore: move namespaces filtering logic to New()
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#1688 RemovePodsViolatingNodeTaints: list only pods that are not failed/suceeded
  pkg/framework/plugins/removepodsviolatingnodetaints/node_taint.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1691 fix(example): list only active pod
  pkg/framework/plugins/example/example.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#1693 refactor: separate eviction constraints to constraints.go
  pkg/framework/plugins/defaultevictor/constraints.go
  pkg/framework/plugins/defaultevictor/defaultevictor.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1694 Extend plugin's New with a context.Context
  pkg/descheduler/descheduler.go
  pkg/framework/fake/plugin/fake.go
  pkg/framework/pluginregistry/pluginregistry.go
  pkg/framework/plugins/defaultevictor/defaultevictor.go
  pkg/framework/plugins/defaultevictor/defaultevictor_test.go
  pkg/framework/plugins/example/example.go
  pkg/framework/plugins/nodeutilization/highnodeutilization.go
  pkg/framework/plugins/nodeutilization/highnodeutilization_test.go
  pkg/framework/plugins/nodeutilization/lownodeutilization.go
  pkg/framework/plugins/nodeutilization/lownodeutilization_test.go
  pkg/framework/plugins/podlifetime/pod_lifetime.go
  pkg/framework/plugins/podlifetime/pod_lifetime_test.go
  pkg/framework/plugins/removeduplicates/removeduplicates.go
  pkg/framework/plugins/removeduplicates/removeduplicates_test.go
  pkg/framework/plugins/removefailedpods/failedpods.go
  pkg/framework/plugins/removefailedpods/failedpods_test.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts.go
  pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts_test.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity.go
  pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity_test.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity.go
  pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity_test.go
  pkg/framework/plugins/removepodsviolatingnodetaints/node_taint.go
  pkg/framework/plugins/removepodsviolatingnodetaints/node_taint_test.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint.go
  pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint_test.go
  pkg/framework/profile/profile.go
  pkg/framework/profile/profile_test.go
  pkg/framework/testing/utils.go
  test/e2e/e2e_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved
